import 'dart:math' as math;

/// Endgame megaprojects — planet-to-stellar-scale builds that consume absurd
/// amounts of mass and energy over very long timescales.
enum MegastructureType {
  orbitalRing, // a ring around a planet
  haloRing, // a small spun habitat ring (a la Halo)
  oNeillCylinder, // rotating cylinder habitat
  dysonSwarm, // independent collectors around a star
  dysonSphere, // full shell around a star
  ringworld, // AU-scale ring around a star
  stellarLifter, // siphons stellar mass
}

/// One construction phase: the mass (kg of refined material) and energy (J) it
/// requires before the next phase can begin. Mutable accumulated contributions.
class BuildPhase {
  final String name;
  final double requiredMass; // kg
  final double requiredEnergy; // J
  double contributedMass;
  double contributedEnergy;

  BuildPhase({
    required this.name,
    required this.requiredMass,
    required this.requiredEnergy,
    this.contributedMass = 0,
    this.contributedEnergy = 0,
  });

  bool get isComplete =>
      contributedMass >= requiredMass && contributedEnergy >= requiredEnergy;

  /// 0..1 progress of this phase (min of the two ratios).
  double get fraction {
    final m = requiredMass <= 0 ? 1.0 : (contributedMass / requiredMass).clamp(0.0, 1.0);
    final e = requiredEnergy <= 0 ? 1.0 : (contributedEnergy / requiredEnergy).clamp(0.0, 1.0);
    return math.min(m, e);
  }
}

/// A megastructure under construction (or complete). Aggregate root for the
/// megastructure context. Built in [phases]; contributions flow in over many
/// ticks from colonies/fleets. Once every phase is complete it becomes
/// [operational] and its [operate] effects (power, habitable area) come online.
class Megastructure {
  final String id;
  final MegastructureType type;
  final List<BuildPhase> phases;

  /// Cached operational parameters (set by the factories).
  final double designOutputWatts; // power produced when operational (Dyson)
  final double habitableAreaM2; // living area when operational (rings/cylinders)

  /// On-SITE buffers. Material (kg) must be physically DELIVERED here by cargo
  /// craft; energy (J) must be generated by on-site / connected power plants.
  /// Construction consumes from these — nothing teleports from a remote colony.
  double siteMaterial = 0;
  double siteEnergy = 0;

  /// On-site power generation (W) from co-located/beamed power plants. This is
  /// the only energy the build can draw — no grid teleport. A completed Dyson
  /// can power the next one (its [currentPowerOutput] can feed a site).
  double siteGenerationWatts = 0;

  Megastructure({
    required this.id,
    required this.type,
    required this.phases,
    this.designOutputWatts = 0,
    this.habitableAreaM2 = 0,
  });

  // ---- Progress ----

  int get completedPhases => phases.where((p) => p.isComplete).length;
  bool get isComplete => phases.isNotEmpty && phases.every((p) => p.isComplete);
  bool get operational => isComplete;

  // ---- Operational output (only once complete) ----

  /// Power produced (W) — Dyson swarms/spheres capture stellar luminosity.
  double get currentPowerOutput => operational ? designOutputWatts : 0;

  /// Habitable living area (m^2) — rings/cylinders, once built.
  double get currentHabitableArea => operational ? habitableAreaM2 : 0;

  /// Population the structure can house (~1 person per 200 m^2).
  int get populationCapacity => (currentHabitableArea / 200).floor();

  /// The first not-yet-complete phase, or null when finished.
  BuildPhase? get currentPhase {
    for (final p in phases) {
      if (!p.isComplete) return p;
    }
    return null;
  }

  double get totalRequiredMass =>
      phases.fold(0.0, (s, p) => s + p.requiredMass);
  double get totalRequiredEnergy =>
      phases.fold(0.0, (s, p) => s + p.requiredEnergy);

  /// Overall build progress 0..1 across all phases (mass+energy weighted).
  double get progress {
    final reqM = totalRequiredMass;
    final reqE = totalRequiredEnergy;
    if (reqM <= 0 && reqE <= 0) return 1.0;
    final gotM = phases.fold(0.0, (s, p) => s + math.min(p.contributedMass, p.requiredMass));
    final gotE = phases.fold(0.0, (s, p) => s + math.min(p.contributedEnergy, p.requiredEnergy));
    final mFrac = reqM <= 0 ? 1.0 : gotM / reqM;
    final eFrac = reqE <= 0 ? 1.0 : gotE / reqE;
    return ((mFrac + eFrac) / 2).clamp(0.0, 1.0);
  }

  /// Cargo craft delivers [kg] of structural material to the build site.
  void deliverMaterial(double kg) {
    if (kg > 0) siteMaterial += kg;
  }

  /// On-site / connected power plants add [joules] of construction energy.
  void deliverEnergy(double joules) {
    if (joules > 0) siteEnergy += joules;
  }

  /// Pour resources into the CURRENT phase only (no overflow to later phases —
  /// you must finish a phase before the next accepts material). Excess beyond
  /// the current phase's requirement is ignored (lost margin), keeping each
  /// phase a distinct gated milestone.
  void contribute({double mass = 0, double energy = 0}) {
    final phase = currentPhase;
    if (phase == null) return;
    phase.contributedMass = math.min(phase.requiredMass, phase.contributedMass + mass);
    phase.contributedEnergy = math.min(phase.requiredEnergy, phase.contributedEnergy + energy);
  }

  // ---- Factories: real-ish scale requirements ----

  static List<BuildPhase> _phases(String prefix, double totalMass, double totalEnergy, int n) {
    // Escalating phases: each costs more than the last (geometric growth).
    final weights = [for (var i = 0; i < n; i++) math.pow(1.6, i).toDouble()];
    final wSum = weights.fold(0.0, (a, b) => a + b);
    return [
      for (var i = 0; i < n; i++)
        BuildPhase(
          name: '$prefix phase ${i + 1}',
          requiredMass: totalMass * weights[i] / wSum,
          requiredEnergy: totalEnergy * weights[i] / wSum,
        ),
    ];
  }

  factory Megastructure.haloRing({required String id, required double radius}) {
    // ~10 km wide band, steel-ish areal density ~1e5 kg/m^2.
    final area = 2 * math.pi * radius * 1.0e4;
    final mass = area * 1.0e5;
    final energy = mass * 5.0e7; // ~refining + lift energy per kg
    return Megastructure(
      id: id,
      type: MegastructureType.haloRing,
      phases: _phases('Halo', mass, energy, 4),
      habitableAreaM2: area,
    );
  }

  factory Megastructure.orbitalRing({required String id, required double radius}) {
    final area = 2 * math.pi * radius * 2.0e3;
    final mass = area * 5.0e4;
    return Megastructure(
      id: id,
      type: MegastructureType.orbitalRing,
      phases: _phases('Orbital ring', mass, mass * 4.0e7, 5),
      habitableAreaM2: area,
    );
  }

  factory Megastructure.oNeillCylinder({
    required String id,
    required double radius,
    required double length,
  }) {
    final area = 2 * math.pi * radius * length; // inner habitable surface
    final mass = area * 8.0e4;
    return Megastructure(
      id: id,
      type: MegastructureType.oNeillCylinder,
      phases: _phases('O\'Neill', mass, mass * 4.0e7, 3),
      habitableAreaM2: area,
    );
  }

  factory Megastructure.dysonSwarm({required String id, required double starLuminosity}) {
    // Swarm of collectors capturing a fraction of the star's output.
    final collectorMass = 1.0e19; // ~asteroid-belt scale
    return Megastructure(
      id: id,
      type: MegastructureType.dysonSwarm,
      phases: _phases('Dyson swarm', collectorMass, collectorMass * 1.0e8, 6),
      // Operational: capture ~10% of stellar luminosity.
      designOutputWatts: starLuminosity * 0.10,
    );
  }

  factory Megastructure.dysonSphere({
    required String id,
    required double starRadius,
    required double starLuminosity,
  }) {
    // Full shell at ~1 AU. Enormous.
    const au = 1.495978707e11;
    final shellArea = 4 * math.pi * au * au;
    final mass = shellArea * 1.0e3; // thin shell, still ~2.8e26 kg
    return Megastructure(
      id: id,
      type: MegastructureType.dysonSphere,
      phases: _phases('Dyson sphere', mass, mass * 1.0e8, 10),
      designOutputWatts: starLuminosity * 0.99,
    );
  }

  factory Megastructure.ringworld({required String id, required double starLuminosity}) {
    const au = 1.495978707e11;
    final area = 2 * math.pi * au * 1.6e9; // ~1e6 mile wide band
    final mass = area * 1.0e3;
    return Megastructure(
      id: id,
      type: MegastructureType.ringworld,
      phases: _phases('Ringworld', mass, mass * 1.0e8, 12),
      designOutputWatts: starLuminosity * 0.4,
      habitableAreaM2: area,
    );
  }
}
