import 'megastructure.dart';

/// Advances a [Megastructure] build using ONLY its on-site buffers — material
/// physically delivered by cargo craft ([Megastructure.deliverMaterial]) and
/// energy generated by on-site / connected power plants
/// ([Megastructure.deliverEnergy]). Nothing teleports from a remote colony:
/// if there's no delivered material or no local power, the build stalls.
///
/// Each call pushes as much of the on-site buffer as the CURRENT phase still
/// needs into the structure, then checks for milestone completions. Returns
/// human-readable milestone strings the application turns into events.
class MegastructureConstruction {
  const MegastructureConstruction();

  List<String> advance(Megastructure structure, {required double dt}) {
    if (structure.isComplete) return const [];
    final phaseBefore = structure.completedPhases;

    final phase = structure.currentPhase;
    if (phase != null) {
      // Material from the delivered on-site stockpile.
      final massNeeded = phase.requiredMass - phase.contributedMass;
      if (massNeeded > 0 && structure.siteMaterial > 0) {
        final useMass =
            massNeeded < structure.siteMaterial ? massNeeded : structure.siteMaterial;
        structure.siteMaterial -= useMass;
        structure.contribute(mass: useMass);
      }
      // Energy from the on-site power buffer.
      final energyNeeded = phase.requiredEnergy - phase.contributedEnergy;
      if (energyNeeded > 0 && structure.siteEnergy > 0) {
        final useEnergy =
            energyNeeded < structure.siteEnergy ? energyNeeded : structure.siteEnergy;
        structure.siteEnergy -= useEnergy;
        structure.contribute(energy: useEnergy);
      }
    }

    final events = <String>[];
    for (var i = phaseBefore; i < structure.completedPhases; i++) {
      events.add('${structure.id}: build phase ${i + 1} complete');
    }
    if (structure.isComplete) {
      events.add('${structure.id}: construction complete — operational');
    }
    return events;
  }
}
