import 'dart:typed_data';

import 'package:acro_space_simulator/application/snapshot/world_snapshot.dart';
import 'package:acro_space_simulator/domain/multiplayer/command.dart';
import 'package:acro_space_simulator/domain/multiplayer/player.dart';
import 'package:acro_space_simulator/domain/simulation/epoch.dart';

import 'sim_acro.wire_generated.dart' as gen;

/// Binary wire codec between the Dart domain and the FlatBuffers contract in
/// `wire/sim.fbs`. This is the ONLY hand-written marshalling on either side of
/// the engine bridge — everything else is generated by `flatc`.
///
/// Direction: [encodeWorld]/[decodeWorld] carry the render frame (sim ->
/// engine); [encodeCommands]/[decodeCommands] carry player intent (engine ->
/// sim). Quaternions are written scalar-first (w,x,y,z) to match the domain;
/// the consuming engine reorders/flips for its own convention.
class FlatBufferCodec {
  const FlatBufferCodec();

  // ---------------- sim -> engine: WorldSnapshot ----------------

  Uint8List encodeWorld(WorldSnapshot s) {
    final bodies = [
      for (final b in s.bodies.values)
        gen.BodyFrameObjectBuilder(
          id: b.id,
          pos: gen.Vec3ObjectBuilder(x: b.px, y: b.py, z: b.pz),
          orient: gen.QuatObjectBuilder(w: b.qw, x: b.qx, y: b.qy, z: b.qz),
          radius: b.radius,
        ),
    ];
    final vessels = [
      for (final v in s.vessels.values)
        gen.VesselFrameObjectBuilder(
          id: v.id,
          owner: v.ownerId,
          body: v.body,
          pos: gen.Vec3ObjectBuilder(x: v.px, y: v.py, z: v.pz),
          vel: gen.Vec3ObjectBuilder(x: v.vx, y: v.vy, z: v.vz),
          att: gen.QuatObjectBuilder(w: v.qw, x: v.qx, y: v.qy, z: v.qz),
          spin: gen.Vec3ObjectBuilder(x: v.wx, y: v.wy, z: v.wz),
          throttle: v.throttle,
          onRails: v.onRails,
          landed: v.landed,
          parts: [
            for (final p in v.parts)
              gen.PartFrameObjectBuilder(
                id: p.id,
                type: p.type,
                offset: gen.Vec3ObjectBuilder(x: p.ox, y: p.oy, z: p.oz),
              ),
          ],
          mass: v.mass,
          crew: v.crew,
          resources: [
            for (final r in v.resources)
              gen.ResourceFrameObjectBuilder(
                type: r.type,
                amount: r.amount,
                capacity: r.capacity,
              ),
          ],
          maxTemp: v.maxTemp,
          tempLimit: v.tempLimit,
          apoapsis: v.apoapsis,
          periapsis: v.periapsis,
          period: v.period,
          eccentricity: v.eccentricity,
          inclination: v.inclination,
          semiMajor: v.semiMajor,
          trajectory: [
            for (var k = 0; k + 2 < v.trajectory.length; k += 3)
              gen.Vec3ObjectBuilder(
                x: v.trajectory[k],
                y: v.trajectory[k + 1],
                z: v.trajectory[k + 2],
              ),
          ],
          connected: v.connected,
          commDelay: v.commDelay,
        ),
    ];
    final buildings = [
      for (final b in s.buildings.values)
        gen.BuildingFrameObjectBuilder(
          id: b.id,
          type: b.type,
          colony: b.colonyId,
          body: b.body,
          pos: gen.Vec3ObjectBuilder(x: b.px, y: b.py, z: b.pz),
          orient: gen.QuatObjectBuilder(w: b.qw, x: b.qx, y: b.qy, z: b.qz),
          lat: b.lat,
          lon: b.lon,
        ),
    ];
    final events = [
      for (final e in s.events)
        gen.EventFrameObjectBuilder(
          kind: e.kind,
          subject: e.subject,
          target: e.target,
          magnitude: e.magnitude,
          info: e.info,
        ),
    ];
    return gen.WorldFrameObjectBuilder(
      tick: s.tick,
      epoch: s.epoch,
      fingerprint: s.fingerprint,
      bodies: bodies,
      vessels: vessels,
      buildings: buildings,
      events: events,
    ).toBytes();
  }

  /// Tolerant of partial frames from a foreign encoder (FlatBuffer table fields
  /// are all optional on the wire): a missing struct defaults to zero / identity
  /// rather than throwing, and an id-less vessel/body is skipped.
  WorldSnapshot decodeWorld(Uint8List bytes) {
    final w = gen.WorldFrame(bytes);
    final vessels = <String, VesselSnapshot>{};
    for (final v in w.vessels ?? const <gen.VesselFrame>[]) {
      final id = v.id;
      if (id == null) continue;
      final pos = v.pos, vel = v.vel, att = v.att, spin = v.spin;
      vessels[id] = VesselSnapshot(
        id: id,
        ownerId: v.owner ?? '',
        body: v.body ?? '',
        px: pos?.x ?? 0,
        py: pos?.y ?? 0,
        pz: pos?.z ?? 0,
        vx: vel?.x ?? 0,
        vy: vel?.y ?? 0,
        vz: vel?.z ?? 0,
        qw: att?.w ?? 1,
        qx: att?.x ?? 0,
        qy: att?.y ?? 0,
        qz: att?.z ?? 0,
        wx: spin?.x ?? 0,
        wy: spin?.y ?? 0,
        wz: spin?.z ?? 0,
        throttle: v.throttle,
        onRails: v.onRails,
        landed: v.landed,
        parts: [
          for (final p in v.parts ?? const <gen.PartFrame>[])
            if (p.id != null)
              PartSnapshot(
                id: p.id!,
                type: p.type ?? '',
                ox: p.offset?.x ?? 0,
                oy: p.offset?.y ?? 0,
                oz: p.offset?.z ?? 0,
              ),
        ],
        mass: v.mass,
        crew: v.crew,
        resources: [
          for (final r in v.resources ?? const <gen.ResourceFrame>[])
            ResourceSnapshot(
              type: r.type ?? '',
              amount: r.amount,
              capacity: r.capacity,
            ),
        ],
        maxTemp: v.maxTemp,
        tempLimit: v.tempLimit,
        apoapsis: v.apoapsis,
        periapsis: v.periapsis,
        period: v.period,
        eccentricity: v.eccentricity,
        inclination: v.inclination,
        semiMajor: v.semiMajor,
        trajectory: [
          for (final p in v.trajectory ?? const <gen.Vec3>[]) ...[p.x, p.y, p.z],
        ],
        connected: v.connected,
        commDelay: v.commDelay,
      );
    }
    final bodies = <String, BodySnapshot>{};
    for (final b in w.bodies ?? const <gen.BodyFrame>[]) {
      final id = b.id;
      if (id == null) continue;
      final pos = b.pos, orient = b.orient;
      bodies[id] = BodySnapshot(
        id: id,
        px: pos?.x ?? 0,
        py: pos?.y ?? 0,
        pz: pos?.z ?? 0,
        qw: orient?.w ?? 1,
        qx: orient?.x ?? 0,
        qy: orient?.y ?? 0,
        qz: orient?.z ?? 0,
        radius: b.radius,
      );
    }
    final buildings = <String, BuildingSnapshot>{};
    for (final b in w.buildings ?? const <gen.BuildingFrame>[]) {
      final id = b.id;
      if (id == null) continue;
      final pos = b.pos, orient = b.orient;
      // Namespace by colony — building ids are only colony-scoped.
      buildings['${b.colony ?? ''}/$id'] = BuildingSnapshot(
        id: id,
        type: b.type ?? '',
        colonyId: b.colony ?? '',
        body: b.body ?? '',
        px: pos?.x ?? 0,
        py: pos?.y ?? 0,
        pz: pos?.z ?? 0,
        qw: orient?.w ?? 1,
        qx: orient?.x ?? 0,
        qy: orient?.y ?? 0,
        qz: orient?.z ?? 0,
        lat: b.lat,
        lon: b.lon,
      );
    }
    final events = [
      for (final e in w.events ?? const <gen.EventFrame>[])
        EventSnapshot(
          kind: e.kind ?? '',
          subject: e.subject ?? '',
          target: e.target ?? '',
          magnitude: e.magnitude,
          info: e.info ?? '',
        ),
    ];
    return WorldSnapshot(
      tick: w.tick,
      epoch: w.epoch,
      bodies: bodies,
      vessels: vessels,
      buildings: buildings,
      events: events,
    );
  }

  // ---------------- engine -> sim: CommandBatch ----------------

  Uint8List encodeCommands(CommandBatch batch) {
    final cmds = [for (final c in batch.commands) _envelope(c)];
    return gen.CommandFrameObjectBuilder(
      at: batch.at.seconds,
      cmds: cmds,
    ).toBytes();
  }

  CommandBatch decodeCommands(Uint8List bytes) {
    final f = gen.CommandFrame(bytes);
    final cmds = <SimCommand>[];
    for (final e in f.cmds ?? const <gen.CmdEnvelope>[]) {
      final issuedBy = e.issuedBy;
      if (issuedBy == null) continue; // unattributed command — skip
      final by = PlayerId(issuedBy);
      final tick = e.tick;
      switch (e.cmdType) {
        case gen.CmdTypeId.SetThrottle:
          final c = e.cmd as gen.SetThrottle;
          cmds.add(SetThrottleCommand(by, tick, c.vessel ?? '', c.throttle));
        case gen.CmdTypeId.SeparateStage:
          final c = e.cmd as gen.SeparateStage;
          cmds.add(SeparateStageCommand(by, tick, c.vessel ?? ''));
        case gen.CmdTypeId.SetAttitude:
          final c = e.cmd as gen.SetAttitude;
          final h = c.heading;
          cmds.add(SetAttitudeCommand(
              by, tick, c.vessel ?? '', h?.x ?? 0, h?.y ?? 0, h?.z ?? 0));
        case gen.CmdTypeId.PlaceBuilding:
          final c = e.cmd as gen.PlaceBuilding;
          cmds.add(PlaceBuildingCommand(
              by, tick, c.colony ?? '', c.kind ?? '', c.gx, c.gy));
        case gen.CmdTypeId.ReportTerrainHeight:
          final c = e.cmd as gen.ReportTerrainHeight;
          cmds.add(ReportTerrainHeightCommand(
              by, tick, c.body ?? '', c.lat, c.lon, c.height));
        case gen.CmdTypeId.NONE:
        case null:
          break; // unknown/empty envelope — skip
      }
    }
    return CommandBatch(Epoch(f.at), cmds);
  }

  gen.CmdEnvelopeObjectBuilder _envelope(SimCommand c) => switch (c) {
        SetThrottleCommand x => gen.CmdEnvelopeObjectBuilder(
            issuedBy: x.issuedBy.value,
            tick: x.tick,
            cmdType: gen.CmdTypeId.SetThrottle,
            cmd: gen.SetThrottleObjectBuilder(
                vessel: x.vesselId, throttle: x.throttle),
          ),
        SeparateStageCommand x => gen.CmdEnvelopeObjectBuilder(
            issuedBy: x.issuedBy.value,
            tick: x.tick,
            cmdType: gen.CmdTypeId.SeparateStage,
            cmd: gen.SeparateStageObjectBuilder(vessel: x.vesselId),
          ),
        SetAttitudeCommand x => gen.CmdEnvelopeObjectBuilder(
            issuedBy: x.issuedBy.value,
            tick: x.tick,
            cmdType: gen.CmdTypeId.SetAttitude,
            cmd: gen.SetAttitudeObjectBuilder(
              vessel: x.vesselId,
              heading: gen.Vec3ObjectBuilder(
                  x: x.headingX, y: x.headingY, z: x.headingZ),
            ),
          ),
        PlaceBuildingCommand x => gen.CmdEnvelopeObjectBuilder(
            issuedBy: x.issuedBy.value,
            tick: x.tick,
            cmdType: gen.CmdTypeId.PlaceBuilding,
            cmd: gen.PlaceBuildingObjectBuilder(
              colony: x.colonyId,
              kind: x.buildingType,
              gx: x.gridX,
              gy: x.gridY,
            ),
          ),
        ReportTerrainHeightCommand x => gen.CmdEnvelopeObjectBuilder(
            issuedBy: x.issuedBy.value,
            tick: x.tick,
            cmdType: gen.CmdTypeId.ReportTerrainHeight,
            cmd: gen.ReportTerrainHeightObjectBuilder(
              body: x.body,
              lat: x.lat,
              lon: x.lon,
              height: x.height,
            ),
          ),
      };
}
