// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable, constant_identifier_names

library acro.wire;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


enum CmdTypeId {
  NONE(0),
  SetThrottle(1),
  SeparateStage(2),
  SetAttitude(3),
  PlaceBuilding(4),
  ReportTerrainHeight(5);

  final int value;
  const CmdTypeId(this.value);

  factory CmdTypeId.fromValue(int value) {
    switch (value) {
      case 0: return CmdTypeId.NONE;
      case 1: return CmdTypeId.SetThrottle;
      case 2: return CmdTypeId.SeparateStage;
      case 3: return CmdTypeId.SetAttitude;
      case 4: return CmdTypeId.PlaceBuilding;
      case 5: return CmdTypeId.ReportTerrainHeight;
      default: throw StateError('Invalid value $value for bit flag enum');
    }
  }

  static CmdTypeId? _createOrNull(int? value) =>
      value == null ? null : CmdTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 5;
  static const fb.Reader<CmdTypeId> reader = _CmdTypeIdReader();
}

class _CmdTypeIdReader extends fb.Reader<CmdTypeId> {
  const _CmdTypeIdReader();

  @override
  int get size => 1;

  @override
  CmdTypeId read(fb.BufferContext bc, int offset) =>
      CmdTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class Vec3 {
  Vec3._(this._bc, this._bcOffset);

  static const fb.Reader<Vec3> reader = _Vec3Reader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get x => const fb.Float64Reader().read(_bc, _bcOffset + 0);
  double get y => const fb.Float64Reader().read(_bc, _bcOffset + 8);
  double get z => const fb.Float64Reader().read(_bc, _bcOffset + 16);

  @override
  String toString() {
    return 'Vec3{x: ${x}, y: ${y}, z: ${z}}';
  }
}

class _Vec3Reader extends fb.StructReader<Vec3> {
  const _Vec3Reader();

  @override
  int get size => 24;

  @override
  Vec3 createObject(fb.BufferContext bc, int offset) => 
    Vec3._(bc, offset);
}

class Vec3Builder {
  Vec3Builder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double x, double y, double z) {
    fbBuilder.putFloat64(z);
    fbBuilder.putFloat64(y);
    fbBuilder.putFloat64(x);
    return fbBuilder.offset;
  }

}

class Vec3ObjectBuilder extends fb.ObjectBuilder {
  final double _x;
  final double _y;
  final double _z;

  Vec3ObjectBuilder({
    required double x,
    required double y,
    required double z,
  })
      : _x = x,
        _y = y,
        _z = z;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat64(_z);
    fbBuilder.putFloat64(_y);
    fbBuilder.putFloat64(_x);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Quat {
  Quat._(this._bc, this._bcOffset);

  static const fb.Reader<Quat> reader = _QuatReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get w => const fb.Float64Reader().read(_bc, _bcOffset + 0);
  double get x => const fb.Float64Reader().read(_bc, _bcOffset + 8);
  double get y => const fb.Float64Reader().read(_bc, _bcOffset + 16);
  double get z => const fb.Float64Reader().read(_bc, _bcOffset + 24);

  @override
  String toString() {
    return 'Quat{w: ${w}, x: ${x}, y: ${y}, z: ${z}}';
  }
}

class _QuatReader extends fb.StructReader<Quat> {
  const _QuatReader();

  @override
  int get size => 32;

  @override
  Quat createObject(fb.BufferContext bc, int offset) => 
    Quat._(bc, offset);
}

class QuatBuilder {
  QuatBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  int finish(double w, double x, double y, double z) {
    fbBuilder.putFloat64(z);
    fbBuilder.putFloat64(y);
    fbBuilder.putFloat64(x);
    fbBuilder.putFloat64(w);
    return fbBuilder.offset;
  }

}

class QuatObjectBuilder extends fb.ObjectBuilder {
  final double _w;
  final double _x;
  final double _y;
  final double _z;

  QuatObjectBuilder({
    required double w,
    required double x,
    required double y,
    required double z,
  })
      : _w = w,
        _x = x,
        _y = y,
        _z = z;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.putFloat64(_z);
    fbBuilder.putFloat64(_y);
    fbBuilder.putFloat64(_x);
    fbBuilder.putFloat64(_w);
    return fbBuilder.offset;
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class PartFrame {
  PartFrame._(this._bc, this._bcOffset);
  factory PartFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<PartFrame> reader = _PartFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get id => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get type => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  Vec3? get offset => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'PartFrame{id: ${id}, type: ${type}, offset: ${offset}}';
  }
}

class _PartFrameReader extends fb.TableReader<PartFrame> {
  const _PartFrameReader();

  @override
  PartFrame createObject(fb.BufferContext bc, int offset) => 
    PartFrame._(bc, offset);
}

class PartFrameBuilder {
  PartFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addIdOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addTypeOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addOffset(int offset) {
    fbBuilder.addStruct(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PartFrameObjectBuilder extends fb.ObjectBuilder {
  final String? _id;
  final String? _type;
  final Vec3ObjectBuilder? _offset;

  PartFrameObjectBuilder({
    String? id,
    String? type,
    Vec3ObjectBuilder? offset,
  })
      : _id = id,
        _type = type,
        _offset = offset;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? idOffset = _id == null ? null
        : fbBuilder.writeString(_id!);
    final int? typeOffset = _type == null ? null
        : fbBuilder.writeString(_type!);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, idOffset);
    fbBuilder.addOffset(1, typeOffset);
    if (_offset != null) {
      fbBuilder.addStruct(2, _offset!.finish(fbBuilder));
    }
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ResourceFrame {
  ResourceFrame._(this._bc, this._bcOffset);
  factory ResourceFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ResourceFrame> reader = _ResourceFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get type => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  double get amount => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 6, 0.0);
  double get capacity => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 8, 0.0);

  @override
  String toString() {
    return 'ResourceFrame{type: ${type}, amount: ${amount}, capacity: ${capacity}}';
  }
}

class _ResourceFrameReader extends fb.TableReader<ResourceFrame> {
  const _ResourceFrameReader();

  @override
  ResourceFrame createObject(fb.BufferContext bc, int offset) => 
    ResourceFrame._(bc, offset);
}

class ResourceFrameBuilder {
  ResourceFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addTypeOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addAmount(double? amount) {
    fbBuilder.addFloat64(1, amount);
    return fbBuilder.offset;
  }
  int addCapacity(double? capacity) {
    fbBuilder.addFloat64(2, capacity);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ResourceFrameObjectBuilder extends fb.ObjectBuilder {
  final String? _type;
  final double? _amount;
  final double? _capacity;

  ResourceFrameObjectBuilder({
    String? type,
    double? amount,
    double? capacity,
  })
      : _type = type,
        _amount = amount,
        _capacity = capacity;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? typeOffset = _type == null ? null
        : fbBuilder.writeString(_type!);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, typeOffset);
    fbBuilder.addFloat64(1, _amount);
    fbBuilder.addFloat64(2, _capacity);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class VesselFrame {
  VesselFrame._(this._bc, this._bcOffset);
  factory VesselFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VesselFrame> reader = _VesselFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get id => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get owner => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get body => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  Vec3? get pos => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 10);
  Vec3? get vel => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 12);
  Quat? get att => Quat.reader.vTableGetNullable(_bc, _bcOffset, 14);
  Vec3? get spin => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 16);
  double get throttle => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 18, 0.0);
  bool get onRails => const fb.BoolReader().vTableGet(_bc, _bcOffset, 20, false);
  bool get landed => const fb.BoolReader().vTableGet(_bc, _bcOffset, 22, false);
  List<PartFrame>? get parts => const fb.ListReader<PartFrame>(PartFrame.reader).vTableGetNullable(_bc, _bcOffset, 24);
  double get mass => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 26, 0.0);
  int get crew => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 28, 0);
  List<ResourceFrame>? get resources => const fb.ListReader<ResourceFrame>(ResourceFrame.reader).vTableGetNullable(_bc, _bcOffset, 30);
  double get maxTemp => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 32, 0.0);
  double get tempLimit => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 34, 0.0);

  @override
  String toString() {
    return 'VesselFrame{id: ${id}, owner: ${owner}, body: ${body}, pos: ${pos}, vel: ${vel}, att: ${att}, spin: ${spin}, throttle: ${throttle}, onRails: ${onRails}, landed: ${landed}, parts: ${parts}, mass: ${mass}, crew: ${crew}, resources: ${resources}, maxTemp: ${maxTemp}, tempLimit: ${tempLimit}}';
  }
}

class _VesselFrameReader extends fb.TableReader<VesselFrame> {
  const _VesselFrameReader();

  @override
  VesselFrame createObject(fb.BufferContext bc, int offset) => 
    VesselFrame._(bc, offset);
}

class VesselFrameBuilder {
  VesselFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(16);
  }

  int addIdOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addOwnerOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addBodyOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addPos(int offset) {
    fbBuilder.addStruct(3, offset);
    return fbBuilder.offset;
  }
  int addVel(int offset) {
    fbBuilder.addStruct(4, offset);
    return fbBuilder.offset;
  }
  int addAtt(int offset) {
    fbBuilder.addStruct(5, offset);
    return fbBuilder.offset;
  }
  int addSpin(int offset) {
    fbBuilder.addStruct(6, offset);
    return fbBuilder.offset;
  }
  int addThrottle(double? throttle) {
    fbBuilder.addFloat64(7, throttle);
    return fbBuilder.offset;
  }
  int addOnRails(bool? onRails) {
    fbBuilder.addBool(8, onRails);
    return fbBuilder.offset;
  }
  int addLanded(bool? landed) {
    fbBuilder.addBool(9, landed);
    return fbBuilder.offset;
  }
  int addPartsOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addMass(double? mass) {
    fbBuilder.addFloat64(11, mass);
    return fbBuilder.offset;
  }
  int addCrew(int? crew) {
    fbBuilder.addInt32(12, crew);
    return fbBuilder.offset;
  }
  int addResourcesOffset(int? offset) {
    fbBuilder.addOffset(13, offset);
    return fbBuilder.offset;
  }
  int addMaxTemp(double? maxTemp) {
    fbBuilder.addFloat64(14, maxTemp);
    return fbBuilder.offset;
  }
  int addTempLimit(double? tempLimit) {
    fbBuilder.addFloat64(15, tempLimit);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VesselFrameObjectBuilder extends fb.ObjectBuilder {
  final String? _id;
  final String? _owner;
  final String? _body;
  final Vec3ObjectBuilder? _pos;
  final Vec3ObjectBuilder? _vel;
  final QuatObjectBuilder? _att;
  final Vec3ObjectBuilder? _spin;
  final double? _throttle;
  final bool? _onRails;
  final bool? _landed;
  final List<PartFrameObjectBuilder>? _parts;
  final double? _mass;
  final int? _crew;
  final List<ResourceFrameObjectBuilder>? _resources;
  final double? _maxTemp;
  final double? _tempLimit;

  VesselFrameObjectBuilder({
    String? id,
    String? owner,
    String? body,
    Vec3ObjectBuilder? pos,
    Vec3ObjectBuilder? vel,
    QuatObjectBuilder? att,
    Vec3ObjectBuilder? spin,
    double? throttle,
    bool? onRails,
    bool? landed,
    List<PartFrameObjectBuilder>? parts,
    double? mass,
    int? crew,
    List<ResourceFrameObjectBuilder>? resources,
    double? maxTemp,
    double? tempLimit,
  })
      : _id = id,
        _owner = owner,
        _body = body,
        _pos = pos,
        _vel = vel,
        _att = att,
        _spin = spin,
        _throttle = throttle,
        _onRails = onRails,
        _landed = landed,
        _parts = parts,
        _mass = mass,
        _crew = crew,
        _resources = resources,
        _maxTemp = maxTemp,
        _tempLimit = tempLimit;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? idOffset = _id == null ? null
        : fbBuilder.writeString(_id!);
    final int? ownerOffset = _owner == null ? null
        : fbBuilder.writeString(_owner!);
    final int? bodyOffset = _body == null ? null
        : fbBuilder.writeString(_body!);
    final int? partsOffset = _parts == null ? null
        : fbBuilder.writeList(_parts!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? resourcesOffset = _resources == null ? null
        : fbBuilder.writeList(_resources!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(16);
    fbBuilder.addOffset(0, idOffset);
    fbBuilder.addOffset(1, ownerOffset);
    fbBuilder.addOffset(2, bodyOffset);
    if (_pos != null) {
      fbBuilder.addStruct(3, _pos!.finish(fbBuilder));
    }
    if (_vel != null) {
      fbBuilder.addStruct(4, _vel!.finish(fbBuilder));
    }
    if (_att != null) {
      fbBuilder.addStruct(5, _att!.finish(fbBuilder));
    }
    if (_spin != null) {
      fbBuilder.addStruct(6, _spin!.finish(fbBuilder));
    }
    fbBuilder.addFloat64(7, _throttle);
    fbBuilder.addBool(8, _onRails);
    fbBuilder.addBool(9, _landed);
    fbBuilder.addOffset(10, partsOffset);
    fbBuilder.addFloat64(11, _mass);
    fbBuilder.addInt32(12, _crew);
    fbBuilder.addOffset(13, resourcesOffset);
    fbBuilder.addFloat64(14, _maxTemp);
    fbBuilder.addFloat64(15, _tempLimit);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BuildingFrame {
  BuildingFrame._(this._bc, this._bcOffset);
  factory BuildingFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BuildingFrame> reader = _BuildingFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get id => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get type => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get colony => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  String? get body => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  Vec3? get pos => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 12);
  Quat? get orient => Quat.reader.vTableGetNullable(_bc, _bcOffset, 14);
  double get lat => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 16, 0.0);
  double get lon => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 18, 0.0);

  @override
  String toString() {
    return 'BuildingFrame{id: ${id}, type: ${type}, colony: ${colony}, body: ${body}, pos: ${pos}, orient: ${orient}, lat: ${lat}, lon: ${lon}}';
  }
}

class _BuildingFrameReader extends fb.TableReader<BuildingFrame> {
  const _BuildingFrameReader();

  @override
  BuildingFrame createObject(fb.BufferContext bc, int offset) => 
    BuildingFrame._(bc, offset);
}

class BuildingFrameBuilder {
  BuildingFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(8);
  }

  int addIdOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addTypeOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addColonyOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addBodyOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addPos(int offset) {
    fbBuilder.addStruct(4, offset);
    return fbBuilder.offset;
  }
  int addOrient(int offset) {
    fbBuilder.addStruct(5, offset);
    return fbBuilder.offset;
  }
  int addLat(double? lat) {
    fbBuilder.addFloat64(6, lat);
    return fbBuilder.offset;
  }
  int addLon(double? lon) {
    fbBuilder.addFloat64(7, lon);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BuildingFrameObjectBuilder extends fb.ObjectBuilder {
  final String? _id;
  final String? _type;
  final String? _colony;
  final String? _body;
  final Vec3ObjectBuilder? _pos;
  final QuatObjectBuilder? _orient;
  final double? _lat;
  final double? _lon;

  BuildingFrameObjectBuilder({
    String? id,
    String? type,
    String? colony,
    String? body,
    Vec3ObjectBuilder? pos,
    QuatObjectBuilder? orient,
    double? lat,
    double? lon,
  })
      : _id = id,
        _type = type,
        _colony = colony,
        _body = body,
        _pos = pos,
        _orient = orient,
        _lat = lat,
        _lon = lon;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? idOffset = _id == null ? null
        : fbBuilder.writeString(_id!);
    final int? typeOffset = _type == null ? null
        : fbBuilder.writeString(_type!);
    final int? colonyOffset = _colony == null ? null
        : fbBuilder.writeString(_colony!);
    final int? bodyOffset = _body == null ? null
        : fbBuilder.writeString(_body!);
    fbBuilder.startTable(8);
    fbBuilder.addOffset(0, idOffset);
    fbBuilder.addOffset(1, typeOffset);
    fbBuilder.addOffset(2, colonyOffset);
    fbBuilder.addOffset(3, bodyOffset);
    if (_pos != null) {
      fbBuilder.addStruct(4, _pos!.finish(fbBuilder));
    }
    if (_orient != null) {
      fbBuilder.addStruct(5, _orient!.finish(fbBuilder));
    }
    fbBuilder.addFloat64(6, _lat);
    fbBuilder.addFloat64(7, _lon);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class BodyFrame {
  BodyFrame._(this._bc, this._bcOffset);
  factory BodyFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<BodyFrame> reader = _BodyFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get id => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  Vec3? get pos => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 6);
  Quat? get orient => Quat.reader.vTableGetNullable(_bc, _bcOffset, 8);
  double get radius => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 10, 0.0);

  @override
  String toString() {
    return 'BodyFrame{id: ${id}, pos: ${pos}, orient: ${orient}, radius: ${radius}}';
  }
}

class _BodyFrameReader extends fb.TableReader<BodyFrame> {
  const _BodyFrameReader();

  @override
  BodyFrame createObject(fb.BufferContext bc, int offset) => 
    BodyFrame._(bc, offset);
}

class BodyFrameBuilder {
  BodyFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addIdOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addPos(int offset) {
    fbBuilder.addStruct(1, offset);
    return fbBuilder.offset;
  }
  int addOrient(int offset) {
    fbBuilder.addStruct(2, offset);
    return fbBuilder.offset;
  }
  int addRadius(double? radius) {
    fbBuilder.addFloat64(3, radius);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BodyFrameObjectBuilder extends fb.ObjectBuilder {
  final String? _id;
  final Vec3ObjectBuilder? _pos;
  final QuatObjectBuilder? _orient;
  final double? _radius;

  BodyFrameObjectBuilder({
    String? id,
    Vec3ObjectBuilder? pos,
    QuatObjectBuilder? orient,
    double? radius,
  })
      : _id = id,
        _pos = pos,
        _orient = orient,
        _radius = radius;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? idOffset = _id == null ? null
        : fbBuilder.writeString(_id!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, idOffset);
    if (_pos != null) {
      fbBuilder.addStruct(1, _pos!.finish(fbBuilder));
    }
    if (_orient != null) {
      fbBuilder.addStruct(2, _orient!.finish(fbBuilder));
    }
    fbBuilder.addFloat64(3, _radius);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class EventFrame {
  EventFrame._(this._bc, this._bcOffset);
  factory EventFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<EventFrame> reader = _EventFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get kind => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get subject => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get target => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  double get magnitude => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 10, 0.0);
  String? get info => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 12);

  @override
  String toString() {
    return 'EventFrame{kind: ${kind}, subject: ${subject}, target: ${target}, magnitude: ${magnitude}, info: ${info}}';
  }
}

class _EventFrameReader extends fb.TableReader<EventFrame> {
  const _EventFrameReader();

  @override
  EventFrame createObject(fb.BufferContext bc, int offset) => 
    EventFrame._(bc, offset);
}

class EventFrameBuilder {
  EventFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addKindOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addSubjectOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addTargetOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addMagnitude(double? magnitude) {
    fbBuilder.addFloat64(3, magnitude);
    return fbBuilder.offset;
  }
  int addInfoOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class EventFrameObjectBuilder extends fb.ObjectBuilder {
  final String? _kind;
  final String? _subject;
  final String? _target;
  final double? _magnitude;
  final String? _info;

  EventFrameObjectBuilder({
    String? kind,
    String? subject,
    String? target,
    double? magnitude,
    String? info,
  })
      : _kind = kind,
        _subject = subject,
        _target = target,
        _magnitude = magnitude,
        _info = info;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? kindOffset = _kind == null ? null
        : fbBuilder.writeString(_kind!);
    final int? subjectOffset = _subject == null ? null
        : fbBuilder.writeString(_subject!);
    final int? targetOffset = _target == null ? null
        : fbBuilder.writeString(_target!);
    final int? infoOffset = _info == null ? null
        : fbBuilder.writeString(_info!);
    fbBuilder.startTable(5);
    fbBuilder.addOffset(0, kindOffset);
    fbBuilder.addOffset(1, subjectOffset);
    fbBuilder.addOffset(2, targetOffset);
    fbBuilder.addFloat64(3, _magnitude);
    fbBuilder.addOffset(4, infoOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class WorldFrame {
  WorldFrame._(this._bc, this._bcOffset);
  factory WorldFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<WorldFrame> reader = _WorldFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get tick => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  double get epoch => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 6, 0.0);
  String? get fingerprint => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  List<BodyFrame>? get bodies => const fb.ListReader<BodyFrame>(BodyFrame.reader).vTableGetNullable(_bc, _bcOffset, 10);
  List<VesselFrame>? get vessels => const fb.ListReader<VesselFrame>(VesselFrame.reader).vTableGetNullable(_bc, _bcOffset, 12);
  List<BuildingFrame>? get buildings => const fb.ListReader<BuildingFrame>(BuildingFrame.reader).vTableGetNullable(_bc, _bcOffset, 14);
  List<EventFrame>? get events => const fb.ListReader<EventFrame>(EventFrame.reader).vTableGetNullable(_bc, _bcOffset, 16);

  @override
  String toString() {
    return 'WorldFrame{tick: ${tick}, epoch: ${epoch}, fingerprint: ${fingerprint}, bodies: ${bodies}, vessels: ${vessels}, buildings: ${buildings}, events: ${events}}';
  }
}

class _WorldFrameReader extends fb.TableReader<WorldFrame> {
  const _WorldFrameReader();

  @override
  WorldFrame createObject(fb.BufferContext bc, int offset) => 
    WorldFrame._(bc, offset);
}

class WorldFrameBuilder {
  WorldFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addTick(int? tick) {
    fbBuilder.addInt64(0, tick);
    return fbBuilder.offset;
  }
  int addEpoch(double? epoch) {
    fbBuilder.addFloat64(1, epoch);
    return fbBuilder.offset;
  }
  int addFingerprintOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addBodiesOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addVesselsOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addBuildingsOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addEventsOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class WorldFrameObjectBuilder extends fb.ObjectBuilder {
  final int? _tick;
  final double? _epoch;
  final String? _fingerprint;
  final List<BodyFrameObjectBuilder>? _bodies;
  final List<VesselFrameObjectBuilder>? _vessels;
  final List<BuildingFrameObjectBuilder>? _buildings;
  final List<EventFrameObjectBuilder>? _events;

  WorldFrameObjectBuilder({
    int? tick,
    double? epoch,
    String? fingerprint,
    List<BodyFrameObjectBuilder>? bodies,
    List<VesselFrameObjectBuilder>? vessels,
    List<BuildingFrameObjectBuilder>? buildings,
    List<EventFrameObjectBuilder>? events,
  })
      : _tick = tick,
        _epoch = epoch,
        _fingerprint = fingerprint,
        _bodies = bodies,
        _vessels = vessels,
        _buildings = buildings,
        _events = events;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? fingerprintOffset = _fingerprint == null ? null
        : fbBuilder.writeString(_fingerprint!);
    final int? bodiesOffset = _bodies == null ? null
        : fbBuilder.writeList(_bodies!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? vesselsOffset = _vessels == null ? null
        : fbBuilder.writeList(_vessels!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? buildingsOffset = _buildings == null ? null
        : fbBuilder.writeList(_buildings!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? eventsOffset = _events == null ? null
        : fbBuilder.writeList(_events!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(7);
    fbBuilder.addInt64(0, _tick);
    fbBuilder.addFloat64(1, _epoch);
    fbBuilder.addOffset(2, fingerprintOffset);
    fbBuilder.addOffset(3, bodiesOffset);
    fbBuilder.addOffset(4, vesselsOffset);
    fbBuilder.addOffset(5, buildingsOffset);
    fbBuilder.addOffset(6, eventsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class SetThrottle {
  SetThrottle._(this._bc, this._bcOffset);
  factory SetThrottle(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SetThrottle> reader = _SetThrottleReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get vessel => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  double get throttle => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 6, 0.0);

  @override
  String toString() {
    return 'SetThrottle{vessel: ${vessel}, throttle: ${throttle}}';
  }
}

class _SetThrottleReader extends fb.TableReader<SetThrottle> {
  const _SetThrottleReader();

  @override
  SetThrottle createObject(fb.BufferContext bc, int offset) => 
    SetThrottle._(bc, offset);
}

class SetThrottleBuilder {
  SetThrottleBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addVesselOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addThrottle(double? throttle) {
    fbBuilder.addFloat64(1, throttle);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SetThrottleObjectBuilder extends fb.ObjectBuilder {
  final String? _vessel;
  final double? _throttle;

  SetThrottleObjectBuilder({
    String? vessel,
    double? throttle,
  })
      : _vessel = vessel,
        _throttle = throttle;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? vesselOffset = _vessel == null ? null
        : fbBuilder.writeString(_vessel!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, vesselOffset);
    fbBuilder.addFloat64(1, _throttle);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class SeparateStage {
  SeparateStage._(this._bc, this._bcOffset);
  factory SeparateStage(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SeparateStage> reader = _SeparateStageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get vessel => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'SeparateStage{vessel: ${vessel}}';
  }
}

class _SeparateStageReader extends fb.TableReader<SeparateStage> {
  const _SeparateStageReader();

  @override
  SeparateStage createObject(fb.BufferContext bc, int offset) => 
    SeparateStage._(bc, offset);
}

class SeparateStageBuilder {
  SeparateStageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addVesselOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SeparateStageObjectBuilder extends fb.ObjectBuilder {
  final String? _vessel;

  SeparateStageObjectBuilder({
    String? vessel,
  })
      : _vessel = vessel;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? vesselOffset = _vessel == null ? null
        : fbBuilder.writeString(_vessel!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, vesselOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class SetAttitude {
  SetAttitude._(this._bc, this._bcOffset);
  factory SetAttitude(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<SetAttitude> reader = _SetAttitudeReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get vessel => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  Vec3? get heading => Vec3.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'SetAttitude{vessel: ${vessel}, heading: ${heading}}';
  }
}

class _SetAttitudeReader extends fb.TableReader<SetAttitude> {
  const _SetAttitudeReader();

  @override
  SetAttitude createObject(fb.BufferContext bc, int offset) => 
    SetAttitude._(bc, offset);
}

class SetAttitudeBuilder {
  SetAttitudeBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addVesselOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addHeading(int offset) {
    fbBuilder.addStruct(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class SetAttitudeObjectBuilder extends fb.ObjectBuilder {
  final String? _vessel;
  final Vec3ObjectBuilder? _heading;

  SetAttitudeObjectBuilder({
    String? vessel,
    Vec3ObjectBuilder? heading,
  })
      : _vessel = vessel,
        _heading = heading;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? vesselOffset = _vessel == null ? null
        : fbBuilder.writeString(_vessel!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, vesselOffset);
    if (_heading != null) {
      fbBuilder.addStruct(1, _heading!.finish(fbBuilder));
    }
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class PlaceBuilding {
  PlaceBuilding._(this._bc, this._bcOffset);
  factory PlaceBuilding(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<PlaceBuilding> reader = _PlaceBuildingReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get colony => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get kind => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get gx => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get gy => const fb.Int32Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'PlaceBuilding{colony: ${colony}, kind: ${kind}, gx: ${gx}, gy: ${gy}}';
  }
}

class _PlaceBuildingReader extends fb.TableReader<PlaceBuilding> {
  const _PlaceBuildingReader();

  @override
  PlaceBuilding createObject(fb.BufferContext bc, int offset) => 
    PlaceBuilding._(bc, offset);
}

class PlaceBuildingBuilder {
  PlaceBuildingBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addColonyOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addKindOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addGx(int? gx) {
    fbBuilder.addInt32(2, gx);
    return fbBuilder.offset;
  }
  int addGy(int? gy) {
    fbBuilder.addInt32(3, gy);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PlaceBuildingObjectBuilder extends fb.ObjectBuilder {
  final String? _colony;
  final String? _kind;
  final int? _gx;
  final int? _gy;

  PlaceBuildingObjectBuilder({
    String? colony,
    String? kind,
    int? gx,
    int? gy,
  })
      : _colony = colony,
        _kind = kind,
        _gx = gx,
        _gy = gy;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? colonyOffset = _colony == null ? null
        : fbBuilder.writeString(_colony!);
    final int? kindOffset = _kind == null ? null
        : fbBuilder.writeString(_kind!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, colonyOffset);
    fbBuilder.addOffset(1, kindOffset);
    fbBuilder.addInt32(2, _gx);
    fbBuilder.addInt32(3, _gy);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ReportTerrainHeight {
  ReportTerrainHeight._(this._bc, this._bcOffset);
  factory ReportTerrainHeight(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ReportTerrainHeight> reader = _ReportTerrainHeightReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get body => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  double get lat => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 6, 0.0);
  double get lon => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 8, 0.0);
  double get height => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 10, 0.0);

  @override
  String toString() {
    return 'ReportTerrainHeight{body: ${body}, lat: ${lat}, lon: ${lon}, height: ${height}}';
  }
}

class _ReportTerrainHeightReader extends fb.TableReader<ReportTerrainHeight> {
  const _ReportTerrainHeightReader();

  @override
  ReportTerrainHeight createObject(fb.BufferContext bc, int offset) => 
    ReportTerrainHeight._(bc, offset);
}

class ReportTerrainHeightBuilder {
  ReportTerrainHeightBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addBodyOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addLat(double? lat) {
    fbBuilder.addFloat64(1, lat);
    return fbBuilder.offset;
  }
  int addLon(double? lon) {
    fbBuilder.addFloat64(2, lon);
    return fbBuilder.offset;
  }
  int addHeight(double? height) {
    fbBuilder.addFloat64(3, height);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ReportTerrainHeightObjectBuilder extends fb.ObjectBuilder {
  final String? _body;
  final double? _lat;
  final double? _lon;
  final double? _height;

  ReportTerrainHeightObjectBuilder({
    String? body,
    double? lat,
    double? lon,
    double? height,
  })
      : _body = body,
        _lat = lat,
        _lon = lon,
        _height = height;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? bodyOffset = _body == null ? null
        : fbBuilder.writeString(_body!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, bodyOffset);
    fbBuilder.addFloat64(1, _lat);
    fbBuilder.addFloat64(2, _lon);
    fbBuilder.addFloat64(3, _height);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class CmdEnvelope {
  CmdEnvelope._(this._bc, this._bcOffset);
  factory CmdEnvelope(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<CmdEnvelope> reader = _CmdEnvelopeReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get issuedBy => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get tick => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  CmdTypeId? get cmdType => CmdTypeId._createOrNull(const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 8));
  dynamic get cmd {
    switch (cmdType?.value) {
      case 1: return SetThrottle.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 2: return SeparateStage.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 3: return SetAttitude.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 4: return PlaceBuilding.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 5: return ReportTerrainHeight.reader.vTableGetNullable(_bc, _bcOffset, 10);
      default: return null;
    }
  }

  @override
  String toString() {
    return 'CmdEnvelope{issuedBy: ${issuedBy}, tick: ${tick}, cmdType: ${cmdType}, cmd: ${cmd}}';
  }
}

class _CmdEnvelopeReader extends fb.TableReader<CmdEnvelope> {
  const _CmdEnvelopeReader();

  @override
  CmdEnvelope createObject(fb.BufferContext bc, int offset) => 
    CmdEnvelope._(bc, offset);
}

class CmdEnvelopeBuilder {
  CmdEnvelopeBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addIssuedByOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addTick(int? tick) {
    fbBuilder.addInt64(1, tick);
    return fbBuilder.offset;
  }
  int addCmdType(CmdTypeId? cmdType) {
    fbBuilder.addUint8(2, cmdType?.value);
    return fbBuilder.offset;
  }
  int addCmdOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class CmdEnvelopeObjectBuilder extends fb.ObjectBuilder {
  final String? _issuedBy;
  final int? _tick;
  final CmdTypeId? _cmdType;
  final dynamic _cmd;

  CmdEnvelopeObjectBuilder({
    String? issuedBy,
    int? tick,
    CmdTypeId? cmdType,
    dynamic cmd,
  })
      : _issuedBy = issuedBy,
        _tick = tick,
        _cmdType = cmdType,
        _cmd = cmd;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? issuedByOffset = _issuedBy == null ? null
        : fbBuilder.writeString(_issuedBy!);
    final int? cmdOffset = _cmd?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, issuedByOffset);
    fbBuilder.addInt64(1, _tick);
    fbBuilder.addUint8(2, _cmdType?.value);
    fbBuilder.addOffset(3, cmdOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class CommandFrame {
  CommandFrame._(this._bc, this._bcOffset);
  factory CommandFrame(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<CommandFrame> reader = _CommandFrameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get at => const fb.Float64Reader().vTableGet(_bc, _bcOffset, 4, 0.0);
  List<CmdEnvelope>? get cmds => const fb.ListReader<CmdEnvelope>(CmdEnvelope.reader).vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'CommandFrame{at: ${at}, cmds: ${cmds}}';
  }
}

class _CommandFrameReader extends fb.TableReader<CommandFrame> {
  const _CommandFrameReader();

  @override
  CommandFrame createObject(fb.BufferContext bc, int offset) => 
    CommandFrame._(bc, offset);
}

class CommandFrameBuilder {
  CommandFrameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addAt(double? at) {
    fbBuilder.addFloat64(0, at);
    return fbBuilder.offset;
  }
  int addCmdsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class CommandFrameObjectBuilder extends fb.ObjectBuilder {
  final double? _at;
  final List<CmdEnvelopeObjectBuilder>? _cmds;

  CommandFrameObjectBuilder({
    double? at,
    List<CmdEnvelopeObjectBuilder>? cmds,
  })
      : _at = at,
        _cmds = cmds;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? cmdsOffset = _cmds == null ? null
        : fbBuilder.writeList(_cmds!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(2);
    fbBuilder.addFloat64(0, _at);
    fbBuilder.addOffset(1, cmdsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
