// GENERATED by tool/gen_ue_bindings.dart from wire/sim.fbs — DO NOT EDIT.
// Regenerate: dart run tool/gen_ue_bindings.dart
#pragma once

#include "CoreMinimal.h"
#include "AcroSimTypes.generated.h"

/// One part of a craft (asset key + craft-local offset).
USTRUCT(BlueprintType)
struct FSimPart
{
	GENERATED_BODY()
	UPROPERTY(BlueprintReadOnly) FString Id;
	UPROPERTY(BlueprintReadOnly) FString Type;
	UPROPERTY(BlueprintReadOnly) FVector LocalOffset = FVector::ZeroVector;
};

/// Aggregated resource gauge (summed across parts by type).
USTRUCT(BlueprintType)
struct FSimResource
{
	GENERATED_BODY()
	UPROPERTY(BlueprintReadOnly) FString Type;
	UPROPERTY(BlueprintReadOnly) float Amount = 0.f;
	UPROPERTY(BlueprintReadOnly) float Capacity = 0.f;
};

/// A celestial body, world-space + rebased onto the focus body.
USTRUCT(BlueprintType)
struct FSimBody
{
	GENERATED_BODY()
	UPROPERTY(BlueprintReadOnly) FString Id;
	UPROPERTY(BlueprintReadOnly) FVector Position = FVector::ZeroVector;
	UPROPERTY(BlueprintReadOnly) FQuat Orientation = FQuat::Identity;
	UPROPERTY(BlueprintReadOnly) float RadiusCm = 0.f;
};

/// A vessel, world-space + rebased; Parts compose the craft.
USTRUCT(BlueprintType)
struct FSimVessel
{
	GENERATED_BODY()
	UPROPERTY(BlueprintReadOnly) FString Id;
	UPROPERTY(BlueprintReadOnly) FString Owner;
	UPROPERTY(BlueprintReadOnly) FString Body;
	UPROPERTY(BlueprintReadOnly) FVector Position = FVector::ZeroVector;
	UPROPERTY(BlueprintReadOnly) FVector Velocity = FVector::ZeroVector;
	UPROPERTY(BlueprintReadOnly) FQuat Attitude = FQuat::Identity;
	UPROPERTY(BlueprintReadOnly) FVector AngularVelocity = FVector::ZeroVector;
	UPROPERTY(BlueprintReadOnly) float Throttle = 0.f;
	UPROPERTY(BlueprintReadOnly) bool bOnRails = false;
	UPROPERTY(BlueprintReadOnly) bool bLanded = false;
	UPROPERTY(BlueprintReadOnly) TArray<FSimPart> Parts;
	UPROPERTY(BlueprintReadOnly) float MassKg = 0.f;
	UPROPERTY(BlueprintReadOnly) int32 Crew = 0;
	UPROPERTY(BlueprintReadOnly) TArray<FSimResource> Resources;
	UPROPERTY(BlueprintReadOnly) float MaxTempK = 0.f;
	UPROPERTY(BlueprintReadOnly) float TempLimitK = 0.f;
	UPROPERTY(BlueprintReadOnly) float ApoapsisM = 0.f;
	UPROPERTY(BlueprintReadOnly) float PeriapsisM = 0.f;
	UPROPERTY(BlueprintReadOnly) float PeriodSeconds = 0.f;
	UPROPERTY(BlueprintReadOnly) float Eccentricity = 0.f;
	UPROPERTY(BlueprintReadOnly) float InclinationRad = 0.f;
	UPROPERTY(BlueprintReadOnly) float SemiMajorM = 0.f;
	UPROPERTY(BlueprintReadOnly) TArray<FVector> Trajectory;
	UPROPERTY(BlueprintReadOnly) bool bConnected = false;
	UPROPERTY(BlueprintReadOnly) float CommDelaySeconds = 0.f;
};

/// A colony building, body-LOCAL (parent under the body actor).
USTRUCT(BlueprintType)
struct FSimBuilding
{
	GENERATED_BODY()
	UPROPERTY(BlueprintReadOnly) FString Id;
	UPROPERTY(BlueprintReadOnly) FString Type;
	UPROPERTY(BlueprintReadOnly) FString Colony;
	UPROPERTY(BlueprintReadOnly) FString Body;
	UPROPERTY(BlueprintReadOnly) FVector LocalPosition = FVector::ZeroVector;
	UPROPERTY(BlueprintReadOnly) FQuat LocalOrientation = FQuat::Identity;
	UPROPERTY(BlueprintReadOnly) float Lat = 0.f;
	UPROPERTY(BlueprintReadOnly) float Lon = 0.f;
};

/// A discrete sim event that fired this tick (switch on Kind).
USTRUCT(BlueprintType)
struct FSimEvent
{
	GENERATED_BODY()
	UPROPERTY(BlueprintReadOnly) FString Kind;
	UPROPERTY(BlueprintReadOnly) FString Subject;
	UPROPERTY(BlueprintReadOnly) FString Target;
	UPROPERTY(BlueprintReadOnly) float Magnitude = 0.f;
	UPROPERTY(BlueprintReadOnly) FString Info;
};

