// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIM_ACRO_WIRE_H_
#define FLATBUFFERS_GENERATED_SIM_ACRO_WIRE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace acro {
namespace wire {

struct Vec3;

struct Quat;

struct PartFrame;
struct PartFrameBuilder;

struct ResourceFrame;
struct ResourceFrameBuilder;

struct VesselFrame;
struct VesselFrameBuilder;

struct BuildingFrame;
struct BuildingFrameBuilder;

struct BodyFrame;
struct BodyFrameBuilder;

struct GasFraction;
struct GasFractionBuilder;

struct BodyDescriptor;
struct BodyDescriptorBuilder;

struct EventFrame;
struct EventFrameBuilder;

struct WorldFrame;
struct WorldFrameBuilder;

struct SetThrottle;
struct SetThrottleBuilder;

struct SeparateStage;
struct SeparateStageBuilder;

struct SetAttitude;
struct SetAttitudeBuilder;

struct PlaceBuilding;
struct PlaceBuildingBuilder;

struct ReportTerrainHeight;
struct ReportTerrainHeightBuilder;

struct CmdEnvelope;
struct CmdEnvelopeBuilder;

struct CommandFrame;
struct CommandFrameBuilder;

enum class BodyKind : uint8_t {
  Rocky = 0,
  Star = 1,
  GasGiant = 2,
  Moon = 3,
  Ice = 4,
  MIN = Rocky,
  MAX = Ice
};

inline const BodyKind (&EnumValuesBodyKind())[5] {
  static const BodyKind values[] = {
    BodyKind::Rocky,
    BodyKind::Star,
    BodyKind::GasGiant,
    BodyKind::Moon,
    BodyKind::Ice
  };
  return values;
}

inline const char * const *EnumNamesBodyKind() {
  static const char * const names[6] = {
    "Rocky",
    "Star",
    "GasGiant",
    "Moon",
    "Ice",
    nullptr
  };
  return names;
}

inline const char *EnumNameBodyKind(BodyKind e) {
  if (::flatbuffers::IsOutRange(e, BodyKind::Rocky, BodyKind::Ice)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBodyKind()[index];
}

enum class AtmosphereGas : uint8_t {
  Nitrogen = 0,
  Oxygen = 1,
  CarbonDioxide = 2,
  Hydrogen = 3,
  Helium = 4,
  Methane = 5,
  Argon = 6,
  Water = 7,
  MIN = Nitrogen,
  MAX = Water
};

inline const AtmosphereGas (&EnumValuesAtmosphereGas())[8] {
  static const AtmosphereGas values[] = {
    AtmosphereGas::Nitrogen,
    AtmosphereGas::Oxygen,
    AtmosphereGas::CarbonDioxide,
    AtmosphereGas::Hydrogen,
    AtmosphereGas::Helium,
    AtmosphereGas::Methane,
    AtmosphereGas::Argon,
    AtmosphereGas::Water
  };
  return values;
}

inline const char * const *EnumNamesAtmosphereGas() {
  static const char * const names[9] = {
    "Nitrogen",
    "Oxygen",
    "CarbonDioxide",
    "Hydrogen",
    "Helium",
    "Methane",
    "Argon",
    "Water",
    nullptr
  };
  return names;
}

inline const char *EnumNameAtmosphereGas(AtmosphereGas e) {
  if (::flatbuffers::IsOutRange(e, AtmosphereGas::Nitrogen, AtmosphereGas::Water)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAtmosphereGas()[index];
}

enum class Cmd : uint8_t {
  NONE = 0,
  SetThrottle = 1,
  SeparateStage = 2,
  SetAttitude = 3,
  PlaceBuilding = 4,
  ReportTerrainHeight = 5,
  MIN = NONE,
  MAX = ReportTerrainHeight
};

inline const Cmd (&EnumValuesCmd())[6] {
  static const Cmd values[] = {
    Cmd::NONE,
    Cmd::SetThrottle,
    Cmd::SeparateStage,
    Cmd::SetAttitude,
    Cmd::PlaceBuilding,
    Cmd::ReportTerrainHeight
  };
  return values;
}

inline const char * const *EnumNamesCmd() {
  static const char * const names[7] = {
    "NONE",
    "SetThrottle",
    "SeparateStage",
    "SetAttitude",
    "PlaceBuilding",
    "ReportTerrainHeight",
    nullptr
  };
  return names;
}

inline const char *EnumNameCmd(Cmd e) {
  if (::flatbuffers::IsOutRange(e, Cmd::NONE, Cmd::ReportTerrainHeight)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCmd()[index];
}

template<typename T> struct CmdTraits {
  static const Cmd enum_value = Cmd::NONE;
};

template<> struct CmdTraits<acro::wire::SetThrottle> {
  static const Cmd enum_value = Cmd::SetThrottle;
};

template<> struct CmdTraits<acro::wire::SeparateStage> {
  static const Cmd enum_value = Cmd::SeparateStage;
};

template<> struct CmdTraits<acro::wire::SetAttitude> {
  static const Cmd enum_value = Cmd::SetAttitude;
};

template<> struct CmdTraits<acro::wire::PlaceBuilding> {
  static const Cmd enum_value = Cmd::PlaceBuilding;
};

template<> struct CmdTraits<acro::wire::ReportTerrainHeight> {
  static const Cmd enum_value = Cmd::ReportTerrainHeight;
};

bool VerifyCmd(::flatbuffers::Verifier &verifier, const void *obj, Cmd type);
bool VerifyCmdVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Cmd> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(double _x, double _y, double _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  double x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Quat FLATBUFFERS_FINAL_CLASS {
 private:
  double w_;
  double x_;
  double y_;
  double z_;

 public:
  Quat()
      : w_(0),
        x_(0),
        y_(0),
        z_(0) {
  }
  Quat(double _w, double _x, double _y, double _z)
      : w_(::flatbuffers::EndianScalar(_w)),
        x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  double w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
  double x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Quat, 32);

struct PartFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_OFFSET = 8
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const acro::wire::Vec3 *offset() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_OFFSET);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_OFFSET, 8) &&
           verifier.EndTable();
  }
};

struct PartFrameBuilder {
  typedef PartFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(PartFrame::VT_ID, id);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(PartFrame::VT_TYPE, type);
  }
  void add_offset(const acro::wire::Vec3 *offset) {
    fbb_.AddStruct(PartFrame::VT_OFFSET, offset);
  }
  explicit PartFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartFrame> CreatePartFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    const acro::wire::Vec3 *offset = nullptr) {
  PartFrameBuilder builder_(_fbb);
  builder_.add_offset(offset);
  builder_.add_type(type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartFrame> CreatePartFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *type = nullptr,
    const acro::wire::Vec3 *offset = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  return acro::wire::CreatePartFrame(
      _fbb,
      id__,
      type__,
      offset);
}

struct ResourceFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ResourceFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_AMOUNT = 6,
    VT_CAPACITY = 8
  };
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  double amount() const {
    return GetField<double>(VT_AMOUNT, 0.0);
  }
  double capacity() const {
    return GetField<double>(VT_CAPACITY, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyField<double>(verifier, VT_AMOUNT, 8) &&
           VerifyField<double>(verifier, VT_CAPACITY, 8) &&
           verifier.EndTable();
  }
};

struct ResourceFrameBuilder {
  typedef ResourceFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(ResourceFrame::VT_TYPE, type);
  }
  void add_amount(double amount) {
    fbb_.AddElement<double>(ResourceFrame::VT_AMOUNT, amount, 0.0);
  }
  void add_capacity(double capacity) {
    fbb_.AddElement<double>(ResourceFrame::VT_CAPACITY, capacity, 0.0);
  }
  explicit ResourceFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ResourceFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ResourceFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ResourceFrame> CreateResourceFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    double amount = 0.0,
    double capacity = 0.0) {
  ResourceFrameBuilder builder_(_fbb);
  builder_.add_capacity(capacity);
  builder_.add_amount(amount);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ResourceFrame> CreateResourceFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *type = nullptr,
    double amount = 0.0,
    double capacity = 0.0) {
  auto type__ = type ? _fbb.CreateString(type) : 0;
  return acro::wire::CreateResourceFrame(
      _fbb,
      type__,
      amount,
      capacity);
}

struct VesselFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VesselFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_OWNER = 6,
    VT_BODY = 8,
    VT_POS = 10,
    VT_VEL = 12,
    VT_ATT = 14,
    VT_SPIN = 16,
    VT_THROTTLE = 18,
    VT_ON_RAILS = 20,
    VT_LANDED = 22,
    VT_PARTS = 24,
    VT_MASS = 26,
    VT_CREW = 28,
    VT_RESOURCES = 30,
    VT_MAX_TEMP = 32,
    VT_TEMP_LIMIT = 34,
    VT_APOAPSIS = 36,
    VT_PERIAPSIS = 38,
    VT_PERIOD = 40,
    VT_ECCENTRICITY = 42,
    VT_INCLINATION = 44,
    VT_SEMI_MAJOR = 46,
    VT_TRAJECTORY = 48,
    VT_CONNECTED = 50,
    VT_COMM_DELAY = 52
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *owner() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OWNER);
  }
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  const acro::wire::Vec3 *pos() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_POS);
  }
  const acro::wire::Vec3 *vel() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_VEL);
  }
  const acro::wire::Quat *att() const {
    return GetStruct<const acro::wire::Quat *>(VT_ATT);
  }
  const acro::wire::Vec3 *spin() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_SPIN);
  }
  double throttle() const {
    return GetField<double>(VT_THROTTLE, 0.0);
  }
  bool on_rails() const {
    return GetField<uint8_t>(VT_ON_RAILS, 0) != 0;
  }
  bool landed() const {
    return GetField<uint8_t>(VT_LANDED, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>> *parts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>> *>(VT_PARTS);
  }
  double mass() const {
    return GetField<double>(VT_MASS, 0.0);
  }
  int32_t crew() const {
    return GetField<int32_t>(VT_CREW, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::ResourceFrame>> *resources() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::ResourceFrame>> *>(VT_RESOURCES);
  }
  double max_temp() const {
    return GetField<double>(VT_MAX_TEMP, 0.0);
  }
  double temp_limit() const {
    return GetField<double>(VT_TEMP_LIMIT, 0.0);
  }
  double apoapsis() const {
    return GetField<double>(VT_APOAPSIS, 0.0);
  }
  double periapsis() const {
    return GetField<double>(VT_PERIAPSIS, 0.0);
  }
  double period() const {
    return GetField<double>(VT_PERIOD, 0.0);
  }
  double eccentricity() const {
    return GetField<double>(VT_ECCENTRICITY, 0.0);
  }
  double inclination() const {
    return GetField<double>(VT_INCLINATION, 0.0);
  }
  double semi_major() const {
    return GetField<double>(VT_SEMI_MAJOR, 0.0);
  }
  const ::flatbuffers::Vector<const acro::wire::Vec3 *> *trajectory() const {
    return GetPointer<const ::flatbuffers::Vector<const acro::wire::Vec3 *> *>(VT_TRAJECTORY);
  }
  bool connected() const {
    return GetField<uint8_t>(VT_CONNECTED, 0) != 0;
  }
  double comm_delay() const {
    return GetField<double>(VT_COMM_DELAY, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_OWNER) &&
           verifier.VerifyString(owner()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_POS, 8) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_VEL, 8) &&
           VerifyField<acro::wire::Quat>(verifier, VT_ATT, 8) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_SPIN, 8) &&
           VerifyField<double>(verifier, VT_THROTTLE, 8) &&
           VerifyField<uint8_t>(verifier, VT_ON_RAILS, 1) &&
           VerifyField<uint8_t>(verifier, VT_LANDED, 1) &&
           VerifyOffset(verifier, VT_PARTS) &&
           verifier.VerifyVector(parts()) &&
           verifier.VerifyVectorOfTables(parts()) &&
           VerifyField<double>(verifier, VT_MASS, 8) &&
           VerifyField<int32_t>(verifier, VT_CREW, 4) &&
           VerifyOffset(verifier, VT_RESOURCES) &&
           verifier.VerifyVector(resources()) &&
           verifier.VerifyVectorOfTables(resources()) &&
           VerifyField<double>(verifier, VT_MAX_TEMP, 8) &&
           VerifyField<double>(verifier, VT_TEMP_LIMIT, 8) &&
           VerifyField<double>(verifier, VT_APOAPSIS, 8) &&
           VerifyField<double>(verifier, VT_PERIAPSIS, 8) &&
           VerifyField<double>(verifier, VT_PERIOD, 8) &&
           VerifyField<double>(verifier, VT_ECCENTRICITY, 8) &&
           VerifyField<double>(verifier, VT_INCLINATION, 8) &&
           VerifyField<double>(verifier, VT_SEMI_MAJOR, 8) &&
           VerifyOffset(verifier, VT_TRAJECTORY) &&
           verifier.VerifyVector(trajectory()) &&
           VerifyField<uint8_t>(verifier, VT_CONNECTED, 1) &&
           VerifyField<double>(verifier, VT_COMM_DELAY, 8) &&
           verifier.EndTable();
  }
};

struct VesselFrameBuilder {
  typedef VesselFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(VesselFrame::VT_ID, id);
  }
  void add_owner(::flatbuffers::Offset<::flatbuffers::String> owner) {
    fbb_.AddOffset(VesselFrame::VT_OWNER, owner);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(VesselFrame::VT_BODY, body);
  }
  void add_pos(const acro::wire::Vec3 *pos) {
    fbb_.AddStruct(VesselFrame::VT_POS, pos);
  }
  void add_vel(const acro::wire::Vec3 *vel) {
    fbb_.AddStruct(VesselFrame::VT_VEL, vel);
  }
  void add_att(const acro::wire::Quat *att) {
    fbb_.AddStruct(VesselFrame::VT_ATT, att);
  }
  void add_spin(const acro::wire::Vec3 *spin) {
    fbb_.AddStruct(VesselFrame::VT_SPIN, spin);
  }
  void add_throttle(double throttle) {
    fbb_.AddElement<double>(VesselFrame::VT_THROTTLE, throttle, 0.0);
  }
  void add_on_rails(bool on_rails) {
    fbb_.AddElement<uint8_t>(VesselFrame::VT_ON_RAILS, static_cast<uint8_t>(on_rails), 0);
  }
  void add_landed(bool landed) {
    fbb_.AddElement<uint8_t>(VesselFrame::VT_LANDED, static_cast<uint8_t>(landed), 0);
  }
  void add_parts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>>> parts) {
    fbb_.AddOffset(VesselFrame::VT_PARTS, parts);
  }
  void add_mass(double mass) {
    fbb_.AddElement<double>(VesselFrame::VT_MASS, mass, 0.0);
  }
  void add_crew(int32_t crew) {
    fbb_.AddElement<int32_t>(VesselFrame::VT_CREW, crew, 0);
  }
  void add_resources(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::ResourceFrame>>> resources) {
    fbb_.AddOffset(VesselFrame::VT_RESOURCES, resources);
  }
  void add_max_temp(double max_temp) {
    fbb_.AddElement<double>(VesselFrame::VT_MAX_TEMP, max_temp, 0.0);
  }
  void add_temp_limit(double temp_limit) {
    fbb_.AddElement<double>(VesselFrame::VT_TEMP_LIMIT, temp_limit, 0.0);
  }
  void add_apoapsis(double apoapsis) {
    fbb_.AddElement<double>(VesselFrame::VT_APOAPSIS, apoapsis, 0.0);
  }
  void add_periapsis(double periapsis) {
    fbb_.AddElement<double>(VesselFrame::VT_PERIAPSIS, periapsis, 0.0);
  }
  void add_period(double period) {
    fbb_.AddElement<double>(VesselFrame::VT_PERIOD, period, 0.0);
  }
  void add_eccentricity(double eccentricity) {
    fbb_.AddElement<double>(VesselFrame::VT_ECCENTRICITY, eccentricity, 0.0);
  }
  void add_inclination(double inclination) {
    fbb_.AddElement<double>(VesselFrame::VT_INCLINATION, inclination, 0.0);
  }
  void add_semi_major(double semi_major) {
    fbb_.AddElement<double>(VesselFrame::VT_SEMI_MAJOR, semi_major, 0.0);
  }
  void add_trajectory(::flatbuffers::Offset<::flatbuffers::Vector<const acro::wire::Vec3 *>> trajectory) {
    fbb_.AddOffset(VesselFrame::VT_TRAJECTORY, trajectory);
  }
  void add_connected(bool connected) {
    fbb_.AddElement<uint8_t>(VesselFrame::VT_CONNECTED, static_cast<uint8_t>(connected), 0);
  }
  void add_comm_delay(double comm_delay) {
    fbb_.AddElement<double>(VesselFrame::VT_COMM_DELAY, comm_delay, 0.0);
  }
  explicit VesselFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VesselFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VesselFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VesselFrame> CreateVesselFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> owner = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Vec3 *vel = nullptr,
    const acro::wire::Quat *att = nullptr,
    const acro::wire::Vec3 *spin = nullptr,
    double throttle = 0.0,
    bool on_rails = false,
    bool landed = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>>> parts = 0,
    double mass = 0.0,
    int32_t crew = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::ResourceFrame>>> resources = 0,
    double max_temp = 0.0,
    double temp_limit = 0.0,
    double apoapsis = 0.0,
    double periapsis = 0.0,
    double period = 0.0,
    double eccentricity = 0.0,
    double inclination = 0.0,
    double semi_major = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const acro::wire::Vec3 *>> trajectory = 0,
    bool connected = false,
    double comm_delay = 0.0) {
  VesselFrameBuilder builder_(_fbb);
  builder_.add_comm_delay(comm_delay);
  builder_.add_semi_major(semi_major);
  builder_.add_inclination(inclination);
  builder_.add_eccentricity(eccentricity);
  builder_.add_period(period);
  builder_.add_periapsis(periapsis);
  builder_.add_apoapsis(apoapsis);
  builder_.add_temp_limit(temp_limit);
  builder_.add_max_temp(max_temp);
  builder_.add_mass(mass);
  builder_.add_throttle(throttle);
  builder_.add_trajectory(trajectory);
  builder_.add_resources(resources);
  builder_.add_crew(crew);
  builder_.add_parts(parts);
  builder_.add_spin(spin);
  builder_.add_att(att);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  builder_.add_body(body);
  builder_.add_owner(owner);
  builder_.add_id(id);
  builder_.add_connected(connected);
  builder_.add_landed(landed);
  builder_.add_on_rails(on_rails);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VesselFrame> CreateVesselFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *owner = nullptr,
    const char *body = nullptr,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Vec3 *vel = nullptr,
    const acro::wire::Quat *att = nullptr,
    const acro::wire::Vec3 *spin = nullptr,
    double throttle = 0.0,
    bool on_rails = false,
    bool landed = false,
    const std::vector<::flatbuffers::Offset<acro::wire::PartFrame>> *parts = nullptr,
    double mass = 0.0,
    int32_t crew = 0,
    const std::vector<::flatbuffers::Offset<acro::wire::ResourceFrame>> *resources = nullptr,
    double max_temp = 0.0,
    double temp_limit = 0.0,
    double apoapsis = 0.0,
    double periapsis = 0.0,
    double period = 0.0,
    double eccentricity = 0.0,
    double inclination = 0.0,
    double semi_major = 0.0,
    const std::vector<acro::wire::Vec3> *trajectory = nullptr,
    bool connected = false,
    double comm_delay = 0.0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto owner__ = owner ? _fbb.CreateString(owner) : 0;
  auto body__ = body ? _fbb.CreateString(body) : 0;
  auto parts__ = parts ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::PartFrame>>(*parts) : 0;
  auto resources__ = resources ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::ResourceFrame>>(*resources) : 0;
  auto trajectory__ = trajectory ? _fbb.CreateVectorOfStructs<acro::wire::Vec3>(*trajectory) : 0;
  return acro::wire::CreateVesselFrame(
      _fbb,
      id__,
      owner__,
      body__,
      pos,
      vel,
      att,
      spin,
      throttle,
      on_rails,
      landed,
      parts__,
      mass,
      crew,
      resources__,
      max_temp,
      temp_limit,
      apoapsis,
      periapsis,
      period,
      eccentricity,
      inclination,
      semi_major,
      trajectory__,
      connected,
      comm_delay);
}

struct BuildingFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BuildingFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COLONY = 8,
    VT_BODY = 10,
    VT_POS = 12,
    VT_ORIENT = 14,
    VT_LAT = 16,
    VT_LON = 18
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const ::flatbuffers::String *colony() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLONY);
  }
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  const acro::wire::Vec3 *pos() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_POS);
  }
  const acro::wire::Quat *orient() const {
    return GetStruct<const acro::wire::Quat *>(VT_ORIENT);
  }
  double lat() const {
    return GetField<double>(VT_LAT, 0.0);
  }
  double lon() const {
    return GetField<double>(VT_LON, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_COLONY) &&
           verifier.VerifyString(colony()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_POS, 8) &&
           VerifyField<acro::wire::Quat>(verifier, VT_ORIENT, 8) &&
           VerifyField<double>(verifier, VT_LAT, 8) &&
           VerifyField<double>(verifier, VT_LON, 8) &&
           verifier.EndTable();
  }
};

struct BuildingFrameBuilder {
  typedef BuildingFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(BuildingFrame::VT_ID, id);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(BuildingFrame::VT_TYPE, type);
  }
  void add_colony(::flatbuffers::Offset<::flatbuffers::String> colony) {
    fbb_.AddOffset(BuildingFrame::VT_COLONY, colony);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(BuildingFrame::VT_BODY, body);
  }
  void add_pos(const acro::wire::Vec3 *pos) {
    fbb_.AddStruct(BuildingFrame::VT_POS, pos);
  }
  void add_orient(const acro::wire::Quat *orient) {
    fbb_.AddStruct(BuildingFrame::VT_ORIENT, orient);
  }
  void add_lat(double lat) {
    fbb_.AddElement<double>(BuildingFrame::VT_LAT, lat, 0.0);
  }
  void add_lon(double lon) {
    fbb_.AddElement<double>(BuildingFrame::VT_LON, lon, 0.0);
  }
  explicit BuildingFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BuildingFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BuildingFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BuildingFrame> CreateBuildingFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> colony = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double lat = 0.0,
    double lon = 0.0) {
  BuildingFrameBuilder builder_(_fbb);
  builder_.add_lon(lon);
  builder_.add_lat(lat);
  builder_.add_orient(orient);
  builder_.add_pos(pos);
  builder_.add_body(body);
  builder_.add_colony(colony);
  builder_.add_type(type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BuildingFrame> CreateBuildingFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *type = nullptr,
    const char *colony = nullptr,
    const char *body = nullptr,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double lat = 0.0,
    double lon = 0.0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  auto colony__ = colony ? _fbb.CreateString(colony) : 0;
  auto body__ = body ? _fbb.CreateString(body) : 0;
  return acro::wire::CreateBuildingFrame(
      _fbb,
      id__,
      type__,
      colony__,
      body__,
      pos,
      orient,
      lat,
      lon);
}

struct BodyFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6,
    VT_ORIENT = 8,
    VT_RADIUS = 10,
    VT_ORBIT = 12
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const acro::wire::Vec3 *pos() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_POS);
  }
  const acro::wire::Quat *orient() const {
    return GetStruct<const acro::wire::Quat *>(VT_ORIENT);
  }
  double radius() const {
    return GetField<double>(VT_RADIUS, 0.0);
  }
  const ::flatbuffers::Vector<const acro::wire::Vec3 *> *orbit() const {
    return GetPointer<const ::flatbuffers::Vector<const acro::wire::Vec3 *> *>(VT_ORBIT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_POS, 8) &&
           VerifyField<acro::wire::Quat>(verifier, VT_ORIENT, 8) &&
           VerifyField<double>(verifier, VT_RADIUS, 8) &&
           VerifyOffset(verifier, VT_ORBIT) &&
           verifier.VerifyVector(orbit()) &&
           verifier.EndTable();
  }
};

struct BodyFrameBuilder {
  typedef BodyFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(BodyFrame::VT_ID, id);
  }
  void add_pos(const acro::wire::Vec3 *pos) {
    fbb_.AddStruct(BodyFrame::VT_POS, pos);
  }
  void add_orient(const acro::wire::Quat *orient) {
    fbb_.AddStruct(BodyFrame::VT_ORIENT, orient);
  }
  void add_radius(double radius) {
    fbb_.AddElement<double>(BodyFrame::VT_RADIUS, radius, 0.0);
  }
  void add_orbit(::flatbuffers::Offset<::flatbuffers::Vector<const acro::wire::Vec3 *>> orbit) {
    fbb_.AddOffset(BodyFrame::VT_ORBIT, orbit);
  }
  explicit BodyFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BodyFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BodyFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BodyFrame> CreateBodyFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double radius = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const acro::wire::Vec3 *>> orbit = 0) {
  BodyFrameBuilder builder_(_fbb);
  builder_.add_radius(radius);
  builder_.add_orbit(orbit);
  builder_.add_orient(orient);
  builder_.add_pos(pos);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BodyFrame> CreateBodyFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double radius = 0.0,
    const std::vector<acro::wire::Vec3> *orbit = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto orbit__ = orbit ? _fbb.CreateVectorOfStructs<acro::wire::Vec3>(*orbit) : 0;
  return acro::wire::CreateBodyFrame(
      _fbb,
      id__,
      pos,
      orient,
      radius,
      orbit__);
}

struct GasFraction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GasFractionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GAS = 4,
    VT_FRACTION = 6
  };
  acro::wire::AtmosphereGas gas() const {
    return static_cast<acro::wire::AtmosphereGas>(GetField<uint8_t>(VT_GAS, 0));
  }
  double fraction() const {
    return GetField<double>(VT_FRACTION, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GAS, 1) &&
           VerifyField<double>(verifier, VT_FRACTION, 8) &&
           verifier.EndTable();
  }
};

struct GasFractionBuilder {
  typedef GasFraction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_gas(acro::wire::AtmosphereGas gas) {
    fbb_.AddElement<uint8_t>(GasFraction::VT_GAS, static_cast<uint8_t>(gas), 0);
  }
  void add_fraction(double fraction) {
    fbb_.AddElement<double>(GasFraction::VT_FRACTION, fraction, 0.0);
  }
  explicit GasFractionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GasFraction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GasFraction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GasFraction> CreateGasFraction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    acro::wire::AtmosphereGas gas = acro::wire::AtmosphereGas::Nitrogen,
    double fraction = 0.0) {
  GasFractionBuilder builder_(_fbb);
  builder_.add_fraction(fraction);
  builder_.add_gas(gas);
  return builder_.Finish();
}

struct BodyDescriptor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyDescriptorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_KIND = 6,
    VT_REFERENCE_RADIUS = 8,
    VT_ALBEDO_KEY = 10,
    VT_HEIGHT_KEY = 12,
    VT_MATERIAL_KEY = 14,
    VT_HEIGHT_SCALE = 16,
    VT_ATMO_PRESENT = 18,
    VT_ATMO_SCALE_HEIGHT = 20,
    VT_ATMO_THICKNESS = 22,
    VT_ATMO_SEA_LEVEL_PRESSURE = 24,
    VT_ATMO_SEA_LEVEL_DENSITY = 26,
    VT_ATMO_SEA_LEVEL_TEMPERATURE = 28,
    VT_ATMO_MEAN_MOLECULAR_WEIGHT = 30,
    VT_ATMO_SCATTER_COLOR = 32,
    VT_ATMO_GASES = 34
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  acro::wire::BodyKind kind() const {
    return static_cast<acro::wire::BodyKind>(GetField<uint8_t>(VT_KIND, 0));
  }
  double reference_radius() const {
    return GetField<double>(VT_REFERENCE_RADIUS, 0.0);
  }
  const ::flatbuffers::String *albedo_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ALBEDO_KEY);
  }
  const ::flatbuffers::String *height_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_HEIGHT_KEY);
  }
  const ::flatbuffers::String *material_key() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MATERIAL_KEY);
  }
  double height_scale() const {
    return GetField<double>(VT_HEIGHT_SCALE, 0.0);
  }
  bool atmo_present() const {
    return GetField<uint8_t>(VT_ATMO_PRESENT, 0) != 0;
  }
  double atmo_scale_height() const {
    return GetField<double>(VT_ATMO_SCALE_HEIGHT, 0.0);
  }
  double atmo_thickness() const {
    return GetField<double>(VT_ATMO_THICKNESS, 0.0);
  }
  double atmo_sea_level_pressure() const {
    return GetField<double>(VT_ATMO_SEA_LEVEL_PRESSURE, 0.0);
  }
  double atmo_sea_level_density() const {
    return GetField<double>(VT_ATMO_SEA_LEVEL_DENSITY, 0.0);
  }
  double atmo_sea_level_temperature() const {
    return GetField<double>(VT_ATMO_SEA_LEVEL_TEMPERATURE, 0.0);
  }
  double atmo_mean_molecular_weight() const {
    return GetField<double>(VT_ATMO_MEAN_MOLECULAR_WEIGHT, 0.0);
  }
  uint32_t atmo_scatter_color() const {
    return GetField<uint32_t>(VT_ATMO_SCATTER_COLOR, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::GasFraction>> *atmo_gases() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::GasFraction>> *>(VT_ATMO_GASES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<uint8_t>(verifier, VT_KIND, 1) &&
           VerifyField<double>(verifier, VT_REFERENCE_RADIUS, 8) &&
           VerifyOffset(verifier, VT_ALBEDO_KEY) &&
           verifier.VerifyString(albedo_key()) &&
           VerifyOffset(verifier, VT_HEIGHT_KEY) &&
           verifier.VerifyString(height_key()) &&
           VerifyOffset(verifier, VT_MATERIAL_KEY) &&
           verifier.VerifyString(material_key()) &&
           VerifyField<double>(verifier, VT_HEIGHT_SCALE, 8) &&
           VerifyField<uint8_t>(verifier, VT_ATMO_PRESENT, 1) &&
           VerifyField<double>(verifier, VT_ATMO_SCALE_HEIGHT, 8) &&
           VerifyField<double>(verifier, VT_ATMO_THICKNESS, 8) &&
           VerifyField<double>(verifier, VT_ATMO_SEA_LEVEL_PRESSURE, 8) &&
           VerifyField<double>(verifier, VT_ATMO_SEA_LEVEL_DENSITY, 8) &&
           VerifyField<double>(verifier, VT_ATMO_SEA_LEVEL_TEMPERATURE, 8) &&
           VerifyField<double>(verifier, VT_ATMO_MEAN_MOLECULAR_WEIGHT, 8) &&
           VerifyField<uint32_t>(verifier, VT_ATMO_SCATTER_COLOR, 4) &&
           VerifyOffset(verifier, VT_ATMO_GASES) &&
           verifier.VerifyVector(atmo_gases()) &&
           verifier.VerifyVectorOfTables(atmo_gases()) &&
           verifier.EndTable();
  }
};

struct BodyDescriptorBuilder {
  typedef BodyDescriptor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(BodyDescriptor::VT_ID, id);
  }
  void add_kind(acro::wire::BodyKind kind) {
    fbb_.AddElement<uint8_t>(BodyDescriptor::VT_KIND, static_cast<uint8_t>(kind), 0);
  }
  void add_reference_radius(double reference_radius) {
    fbb_.AddElement<double>(BodyDescriptor::VT_REFERENCE_RADIUS, reference_radius, 0.0);
  }
  void add_albedo_key(::flatbuffers::Offset<::flatbuffers::String> albedo_key) {
    fbb_.AddOffset(BodyDescriptor::VT_ALBEDO_KEY, albedo_key);
  }
  void add_height_key(::flatbuffers::Offset<::flatbuffers::String> height_key) {
    fbb_.AddOffset(BodyDescriptor::VT_HEIGHT_KEY, height_key);
  }
  void add_material_key(::flatbuffers::Offset<::flatbuffers::String> material_key) {
    fbb_.AddOffset(BodyDescriptor::VT_MATERIAL_KEY, material_key);
  }
  void add_height_scale(double height_scale) {
    fbb_.AddElement<double>(BodyDescriptor::VT_HEIGHT_SCALE, height_scale, 0.0);
  }
  void add_atmo_present(bool atmo_present) {
    fbb_.AddElement<uint8_t>(BodyDescriptor::VT_ATMO_PRESENT, static_cast<uint8_t>(atmo_present), 0);
  }
  void add_atmo_scale_height(double atmo_scale_height) {
    fbb_.AddElement<double>(BodyDescriptor::VT_ATMO_SCALE_HEIGHT, atmo_scale_height, 0.0);
  }
  void add_atmo_thickness(double atmo_thickness) {
    fbb_.AddElement<double>(BodyDescriptor::VT_ATMO_THICKNESS, atmo_thickness, 0.0);
  }
  void add_atmo_sea_level_pressure(double atmo_sea_level_pressure) {
    fbb_.AddElement<double>(BodyDescriptor::VT_ATMO_SEA_LEVEL_PRESSURE, atmo_sea_level_pressure, 0.0);
  }
  void add_atmo_sea_level_density(double atmo_sea_level_density) {
    fbb_.AddElement<double>(BodyDescriptor::VT_ATMO_SEA_LEVEL_DENSITY, atmo_sea_level_density, 0.0);
  }
  void add_atmo_sea_level_temperature(double atmo_sea_level_temperature) {
    fbb_.AddElement<double>(BodyDescriptor::VT_ATMO_SEA_LEVEL_TEMPERATURE, atmo_sea_level_temperature, 0.0);
  }
  void add_atmo_mean_molecular_weight(double atmo_mean_molecular_weight) {
    fbb_.AddElement<double>(BodyDescriptor::VT_ATMO_MEAN_MOLECULAR_WEIGHT, atmo_mean_molecular_weight, 0.0);
  }
  void add_atmo_scatter_color(uint32_t atmo_scatter_color) {
    fbb_.AddElement<uint32_t>(BodyDescriptor::VT_ATMO_SCATTER_COLOR, atmo_scatter_color, 0);
  }
  void add_atmo_gases(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::GasFraction>>> atmo_gases) {
    fbb_.AddOffset(BodyDescriptor::VT_ATMO_GASES, atmo_gases);
  }
  explicit BodyDescriptorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BodyDescriptor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BodyDescriptor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BodyDescriptor> CreateBodyDescriptor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    acro::wire::BodyKind kind = acro::wire::BodyKind::Rocky,
    double reference_radius = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> albedo_key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> height_key = 0,
    ::flatbuffers::Offset<::flatbuffers::String> material_key = 0,
    double height_scale = 0.0,
    bool atmo_present = false,
    double atmo_scale_height = 0.0,
    double atmo_thickness = 0.0,
    double atmo_sea_level_pressure = 0.0,
    double atmo_sea_level_density = 0.0,
    double atmo_sea_level_temperature = 0.0,
    double atmo_mean_molecular_weight = 0.0,
    uint32_t atmo_scatter_color = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::GasFraction>>> atmo_gases = 0) {
  BodyDescriptorBuilder builder_(_fbb);
  builder_.add_atmo_mean_molecular_weight(atmo_mean_molecular_weight);
  builder_.add_atmo_sea_level_temperature(atmo_sea_level_temperature);
  builder_.add_atmo_sea_level_density(atmo_sea_level_density);
  builder_.add_atmo_sea_level_pressure(atmo_sea_level_pressure);
  builder_.add_atmo_thickness(atmo_thickness);
  builder_.add_atmo_scale_height(atmo_scale_height);
  builder_.add_height_scale(height_scale);
  builder_.add_reference_radius(reference_radius);
  builder_.add_atmo_gases(atmo_gases);
  builder_.add_atmo_scatter_color(atmo_scatter_color);
  builder_.add_material_key(material_key);
  builder_.add_height_key(height_key);
  builder_.add_albedo_key(albedo_key);
  builder_.add_id(id);
  builder_.add_atmo_present(atmo_present);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BodyDescriptor> CreateBodyDescriptorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    acro::wire::BodyKind kind = acro::wire::BodyKind::Rocky,
    double reference_radius = 0.0,
    const char *albedo_key = nullptr,
    const char *height_key = nullptr,
    const char *material_key = nullptr,
    double height_scale = 0.0,
    bool atmo_present = false,
    double atmo_scale_height = 0.0,
    double atmo_thickness = 0.0,
    double atmo_sea_level_pressure = 0.0,
    double atmo_sea_level_density = 0.0,
    double atmo_sea_level_temperature = 0.0,
    double atmo_mean_molecular_weight = 0.0,
    uint32_t atmo_scatter_color = 0,
    const std::vector<::flatbuffers::Offset<acro::wire::GasFraction>> *atmo_gases = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto albedo_key__ = albedo_key ? _fbb.CreateString(albedo_key) : 0;
  auto height_key__ = height_key ? _fbb.CreateString(height_key) : 0;
  auto material_key__ = material_key ? _fbb.CreateString(material_key) : 0;
  auto atmo_gases__ = atmo_gases ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::GasFraction>>(*atmo_gases) : 0;
  return acro::wire::CreateBodyDescriptor(
      _fbb,
      id__,
      kind,
      reference_radius,
      albedo_key__,
      height_key__,
      material_key__,
      height_scale,
      atmo_present,
      atmo_scale_height,
      atmo_thickness,
      atmo_sea_level_pressure,
      atmo_sea_level_density,
      atmo_sea_level_temperature,
      atmo_mean_molecular_weight,
      atmo_scatter_color,
      atmo_gases__);
}

struct EventFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EventFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_SUBJECT = 6,
    VT_TARGET = 8,
    VT_MAGNITUDE = 10,
    VT_INFO = 12
  };
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  const ::flatbuffers::String *subject() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SUBJECT);
  }
  const ::flatbuffers::String *target() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TARGET);
  }
  double magnitude() const {
    return GetField<double>(VT_MAGNITUDE, 0.0);
  }
  const ::flatbuffers::String *info() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INFO);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyOffset(verifier, VT_SUBJECT) &&
           verifier.VerifyString(subject()) &&
           VerifyOffset(verifier, VT_TARGET) &&
           verifier.VerifyString(target()) &&
           VerifyField<double>(verifier, VT_MAGNITUDE, 8) &&
           VerifyOffset(verifier, VT_INFO) &&
           verifier.VerifyString(info()) &&
           verifier.EndTable();
  }
};

struct EventFrameBuilder {
  typedef EventFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(EventFrame::VT_KIND, kind);
  }
  void add_subject(::flatbuffers::Offset<::flatbuffers::String> subject) {
    fbb_.AddOffset(EventFrame::VT_SUBJECT, subject);
  }
  void add_target(::flatbuffers::Offset<::flatbuffers::String> target) {
    fbb_.AddOffset(EventFrame::VT_TARGET, target);
  }
  void add_magnitude(double magnitude) {
    fbb_.AddElement<double>(EventFrame::VT_MAGNITUDE, magnitude, 0.0);
  }
  void add_info(::flatbuffers::Offset<::flatbuffers::String> info) {
    fbb_.AddOffset(EventFrame::VT_INFO, info);
  }
  explicit EventFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EventFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EventFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EventFrame> CreateEventFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    ::flatbuffers::Offset<::flatbuffers::String> subject = 0,
    ::flatbuffers::Offset<::flatbuffers::String> target = 0,
    double magnitude = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> info = 0) {
  EventFrameBuilder builder_(_fbb);
  builder_.add_magnitude(magnitude);
  builder_.add_info(info);
  builder_.add_target(target);
  builder_.add_subject(subject);
  builder_.add_kind(kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<EventFrame> CreateEventFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *kind = nullptr,
    const char *subject = nullptr,
    const char *target = nullptr,
    double magnitude = 0.0,
    const char *info = nullptr) {
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  auto subject__ = subject ? _fbb.CreateString(subject) : 0;
  auto target__ = target ? _fbb.CreateString(target) : 0;
  auto info__ = info ? _fbb.CreateString(info) : 0;
  return acro::wire::CreateEventFrame(
      _fbb,
      kind__,
      subject__,
      target__,
      magnitude,
      info__);
}

struct WorldFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorldFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_EPOCH = 6,
    VT_FINGERPRINT = 8,
    VT_BODIES = 10,
    VT_VESSELS = 12,
    VT_BUILDINGS = 14,
    VT_EVENTS = 16,
    VT_DESCRIPTORS = 18
  };
  int64_t tick() const {
    return GetField<int64_t>(VT_TICK, 0);
  }
  double epoch() const {
    return GetField<double>(VT_EPOCH, 0.0);
  }
  const ::flatbuffers::String *fingerprint() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FINGERPRINT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>> *bodies() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>> *>(VT_BODIES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>> *vessels() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>> *>(VT_VESSELS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>> *buildings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>> *>(VT_BUILDINGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::EventFrame>> *events() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::EventFrame>> *>(VT_EVENTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyDescriptor>> *descriptors() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyDescriptor>> *>(VT_DESCRIPTORS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_TICK, 8) &&
           VerifyField<double>(verifier, VT_EPOCH, 8) &&
           VerifyOffset(verifier, VT_FINGERPRINT) &&
           verifier.VerifyString(fingerprint()) &&
           VerifyOffset(verifier, VT_BODIES) &&
           verifier.VerifyVector(bodies()) &&
           verifier.VerifyVectorOfTables(bodies()) &&
           VerifyOffset(verifier, VT_VESSELS) &&
           verifier.VerifyVector(vessels()) &&
           verifier.VerifyVectorOfTables(vessels()) &&
           VerifyOffset(verifier, VT_BUILDINGS) &&
           verifier.VerifyVector(buildings()) &&
           verifier.VerifyVectorOfTables(buildings()) &&
           VerifyOffset(verifier, VT_EVENTS) &&
           verifier.VerifyVector(events()) &&
           verifier.VerifyVectorOfTables(events()) &&
           VerifyOffset(verifier, VT_DESCRIPTORS) &&
           verifier.VerifyVector(descriptors()) &&
           verifier.VerifyVectorOfTables(descriptors()) &&
           verifier.EndTable();
  }
};

struct WorldFrameBuilder {
  typedef WorldFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick(int64_t tick) {
    fbb_.AddElement<int64_t>(WorldFrame::VT_TICK, tick, 0);
  }
  void add_epoch(double epoch) {
    fbb_.AddElement<double>(WorldFrame::VT_EPOCH, epoch, 0.0);
  }
  void add_fingerprint(::flatbuffers::Offset<::flatbuffers::String> fingerprint) {
    fbb_.AddOffset(WorldFrame::VT_FINGERPRINT, fingerprint);
  }
  void add_bodies(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>>> bodies) {
    fbb_.AddOffset(WorldFrame::VT_BODIES, bodies);
  }
  void add_vessels(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>>> vessels) {
    fbb_.AddOffset(WorldFrame::VT_VESSELS, vessels);
  }
  void add_buildings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>>> buildings) {
    fbb_.AddOffset(WorldFrame::VT_BUILDINGS, buildings);
  }
  void add_events(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::EventFrame>>> events) {
    fbb_.AddOffset(WorldFrame::VT_EVENTS, events);
  }
  void add_descriptors(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyDescriptor>>> descriptors) {
    fbb_.AddOffset(WorldFrame::VT_DESCRIPTORS, descriptors);
  }
  explicit WorldFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WorldFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WorldFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WorldFrame> CreateWorldFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t tick = 0,
    double epoch = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> fingerprint = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>>> bodies = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>>> vessels = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>>> buildings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::EventFrame>>> events = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyDescriptor>>> descriptors = 0) {
  WorldFrameBuilder builder_(_fbb);
  builder_.add_epoch(epoch);
  builder_.add_tick(tick);
  builder_.add_descriptors(descriptors);
  builder_.add_events(events);
  builder_.add_buildings(buildings);
  builder_.add_vessels(vessels);
  builder_.add_bodies(bodies);
  builder_.add_fingerprint(fingerprint);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WorldFrame> CreateWorldFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t tick = 0,
    double epoch = 0.0,
    const char *fingerprint = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::BodyFrame>> *bodies = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::VesselFrame>> *vessels = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::BuildingFrame>> *buildings = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::EventFrame>> *events = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::BodyDescriptor>> *descriptors = nullptr) {
  auto fingerprint__ = fingerprint ? _fbb.CreateString(fingerprint) : 0;
  auto bodies__ = bodies ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::BodyFrame>>(*bodies) : 0;
  auto vessels__ = vessels ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::VesselFrame>>(*vessels) : 0;
  auto buildings__ = buildings ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::BuildingFrame>>(*buildings) : 0;
  auto events__ = events ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::EventFrame>>(*events) : 0;
  auto descriptors__ = descriptors ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::BodyDescriptor>>(*descriptors) : 0;
  return acro::wire::CreateWorldFrame(
      _fbb,
      tick,
      epoch,
      fingerprint__,
      bodies__,
      vessels__,
      buildings__,
      events__,
      descriptors__);
}

struct SetThrottle FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetThrottleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VESSEL = 4,
    VT_THROTTLE = 6
  };
  const ::flatbuffers::String *vessel() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VESSEL);
  }
  double throttle() const {
    return GetField<double>(VT_THROTTLE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VESSEL) &&
           verifier.VerifyString(vessel()) &&
           VerifyField<double>(verifier, VT_THROTTLE, 8) &&
           verifier.EndTable();
  }
};

struct SetThrottleBuilder {
  typedef SetThrottle Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vessel(::flatbuffers::Offset<::flatbuffers::String> vessel) {
    fbb_.AddOffset(SetThrottle::VT_VESSEL, vessel);
  }
  void add_throttle(double throttle) {
    fbb_.AddElement<double>(SetThrottle::VT_THROTTLE, throttle, 0.0);
  }
  explicit SetThrottleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetThrottle> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetThrottle>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetThrottle> CreateSetThrottle(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> vessel = 0,
    double throttle = 0.0) {
  SetThrottleBuilder builder_(_fbb);
  builder_.add_throttle(throttle);
  builder_.add_vessel(vessel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetThrottle> CreateSetThrottleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *vessel = nullptr,
    double throttle = 0.0) {
  auto vessel__ = vessel ? _fbb.CreateString(vessel) : 0;
  return acro::wire::CreateSetThrottle(
      _fbb,
      vessel__,
      throttle);
}

struct SeparateStage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SeparateStageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VESSEL = 4
  };
  const ::flatbuffers::String *vessel() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VESSEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VESSEL) &&
           verifier.VerifyString(vessel()) &&
           verifier.EndTable();
  }
};

struct SeparateStageBuilder {
  typedef SeparateStage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vessel(::flatbuffers::Offset<::flatbuffers::String> vessel) {
    fbb_.AddOffset(SeparateStage::VT_VESSEL, vessel);
  }
  explicit SeparateStageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SeparateStage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SeparateStage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SeparateStage> CreateSeparateStage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> vessel = 0) {
  SeparateStageBuilder builder_(_fbb);
  builder_.add_vessel(vessel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SeparateStage> CreateSeparateStageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *vessel = nullptr) {
  auto vessel__ = vessel ? _fbb.CreateString(vessel) : 0;
  return acro::wire::CreateSeparateStage(
      _fbb,
      vessel__);
}

struct SetAttitude FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetAttitudeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VESSEL = 4,
    VT_HEADING = 6
  };
  const ::flatbuffers::String *vessel() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VESSEL);
  }
  const acro::wire::Vec3 *heading() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_HEADING);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VESSEL) &&
           verifier.VerifyString(vessel()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_HEADING, 8) &&
           verifier.EndTable();
  }
};

struct SetAttitudeBuilder {
  typedef SetAttitude Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vessel(::flatbuffers::Offset<::flatbuffers::String> vessel) {
    fbb_.AddOffset(SetAttitude::VT_VESSEL, vessel);
  }
  void add_heading(const acro::wire::Vec3 *heading) {
    fbb_.AddStruct(SetAttitude::VT_HEADING, heading);
  }
  explicit SetAttitudeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetAttitude> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetAttitude>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetAttitude> CreateSetAttitude(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> vessel = 0,
    const acro::wire::Vec3 *heading = nullptr) {
  SetAttitudeBuilder builder_(_fbb);
  builder_.add_heading(heading);
  builder_.add_vessel(vessel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetAttitude> CreateSetAttitudeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *vessel = nullptr,
    const acro::wire::Vec3 *heading = nullptr) {
  auto vessel__ = vessel ? _fbb.CreateString(vessel) : 0;
  return acro::wire::CreateSetAttitude(
      _fbb,
      vessel__,
      heading);
}

struct PlaceBuilding FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlaceBuildingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLONY = 4,
    VT_KIND = 6,
    VT_GX = 8,
    VT_GY = 10
  };
  const ::flatbuffers::String *colony() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLONY);
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  int32_t gx() const {
    return GetField<int32_t>(VT_GX, 0);
  }
  int32_t gy() const {
    return GetField<int32_t>(VT_GY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COLONY) &&
           verifier.VerifyString(colony()) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyField<int32_t>(verifier, VT_GX, 4) &&
           VerifyField<int32_t>(verifier, VT_GY, 4) &&
           verifier.EndTable();
  }
};

struct PlaceBuildingBuilder {
  typedef PlaceBuilding Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_colony(::flatbuffers::Offset<::flatbuffers::String> colony) {
    fbb_.AddOffset(PlaceBuilding::VT_COLONY, colony);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(PlaceBuilding::VT_KIND, kind);
  }
  void add_gx(int32_t gx) {
    fbb_.AddElement<int32_t>(PlaceBuilding::VT_GX, gx, 0);
  }
  void add_gy(int32_t gy) {
    fbb_.AddElement<int32_t>(PlaceBuilding::VT_GY, gy, 0);
  }
  explicit PlaceBuildingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlaceBuilding> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlaceBuilding>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlaceBuilding> CreatePlaceBuilding(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> colony = 0,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    int32_t gx = 0,
    int32_t gy = 0) {
  PlaceBuildingBuilder builder_(_fbb);
  builder_.add_gy(gy);
  builder_.add_gx(gx);
  builder_.add_kind(kind);
  builder_.add_colony(colony);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PlaceBuilding> CreatePlaceBuildingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *colony = nullptr,
    const char *kind = nullptr,
    int32_t gx = 0,
    int32_t gy = 0) {
  auto colony__ = colony ? _fbb.CreateString(colony) : 0;
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  return acro::wire::CreatePlaceBuilding(
      _fbb,
      colony__,
      kind__,
      gx,
      gy);
}

struct ReportTerrainHeight FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReportTerrainHeightBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY = 4,
    VT_LAT = 6,
    VT_LON = 8,
    VT_HEIGHT = 10
  };
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  double lat() const {
    return GetField<double>(VT_LAT, 0.0);
  }
  double lon() const {
    return GetField<double>(VT_LON, 0.0);
  }
  double height() const {
    return GetField<double>(VT_HEIGHT, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyField<double>(verifier, VT_LAT, 8) &&
           VerifyField<double>(verifier, VT_LON, 8) &&
           VerifyField<double>(verifier, VT_HEIGHT, 8) &&
           verifier.EndTable();
  }
};

struct ReportTerrainHeightBuilder {
  typedef ReportTerrainHeight Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(ReportTerrainHeight::VT_BODY, body);
  }
  void add_lat(double lat) {
    fbb_.AddElement<double>(ReportTerrainHeight::VT_LAT, lat, 0.0);
  }
  void add_lon(double lon) {
    fbb_.AddElement<double>(ReportTerrainHeight::VT_LON, lon, 0.0);
  }
  void add_height(double height) {
    fbb_.AddElement<double>(ReportTerrainHeight::VT_HEIGHT, height, 0.0);
  }
  explicit ReportTerrainHeightBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReportTerrainHeight> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReportTerrainHeight>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReportTerrainHeight> CreateReportTerrainHeight(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    double lat = 0.0,
    double lon = 0.0,
    double height = 0.0) {
  ReportTerrainHeightBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_lon(lon);
  builder_.add_lat(lat);
  builder_.add_body(body);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReportTerrainHeight> CreateReportTerrainHeightDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *body = nullptr,
    double lat = 0.0,
    double lon = 0.0,
    double height = 0.0) {
  auto body__ = body ? _fbb.CreateString(body) : 0;
  return acro::wire::CreateReportTerrainHeight(
      _fbb,
      body__,
      lat,
      lon,
      height);
}

struct CmdEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ISSUED_BY = 4,
    VT_TICK = 6,
    VT_CMD_TYPE = 8,
    VT_CMD = 10
  };
  const ::flatbuffers::String *issued_by() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ISSUED_BY);
  }
  int64_t tick() const {
    return GetField<int64_t>(VT_TICK, 0);
  }
  acro::wire::Cmd cmd_type() const {
    return static_cast<acro::wire::Cmd>(GetField<uint8_t>(VT_CMD_TYPE, 0));
  }
  const void *cmd() const {
    return GetPointer<const void *>(VT_CMD);
  }
  template<typename T> const T *cmd_as() const;
  const acro::wire::SetThrottle *cmd_as_SetThrottle() const {
    return cmd_type() == acro::wire::Cmd::SetThrottle ? static_cast<const acro::wire::SetThrottle *>(cmd()) : nullptr;
  }
  const acro::wire::SeparateStage *cmd_as_SeparateStage() const {
    return cmd_type() == acro::wire::Cmd::SeparateStage ? static_cast<const acro::wire::SeparateStage *>(cmd()) : nullptr;
  }
  const acro::wire::SetAttitude *cmd_as_SetAttitude() const {
    return cmd_type() == acro::wire::Cmd::SetAttitude ? static_cast<const acro::wire::SetAttitude *>(cmd()) : nullptr;
  }
  const acro::wire::PlaceBuilding *cmd_as_PlaceBuilding() const {
    return cmd_type() == acro::wire::Cmd::PlaceBuilding ? static_cast<const acro::wire::PlaceBuilding *>(cmd()) : nullptr;
  }
  const acro::wire::ReportTerrainHeight *cmd_as_ReportTerrainHeight() const {
    return cmd_type() == acro::wire::Cmd::ReportTerrainHeight ? static_cast<const acro::wire::ReportTerrainHeight *>(cmd()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ISSUED_BY) &&
           verifier.VerifyString(issued_by()) &&
           VerifyField<int64_t>(verifier, VT_TICK, 8) &&
           VerifyField<uint8_t>(verifier, VT_CMD_TYPE, 1) &&
           VerifyOffset(verifier, VT_CMD) &&
           VerifyCmd(verifier, cmd(), cmd_type()) &&
           verifier.EndTable();
  }
};

template<> inline const acro::wire::SetThrottle *CmdEnvelope::cmd_as<acro::wire::SetThrottle>() const {
  return cmd_as_SetThrottle();
}

template<> inline const acro::wire::SeparateStage *CmdEnvelope::cmd_as<acro::wire::SeparateStage>() const {
  return cmd_as_SeparateStage();
}

template<> inline const acro::wire::SetAttitude *CmdEnvelope::cmd_as<acro::wire::SetAttitude>() const {
  return cmd_as_SetAttitude();
}

template<> inline const acro::wire::PlaceBuilding *CmdEnvelope::cmd_as<acro::wire::PlaceBuilding>() const {
  return cmd_as_PlaceBuilding();
}

template<> inline const acro::wire::ReportTerrainHeight *CmdEnvelope::cmd_as<acro::wire::ReportTerrainHeight>() const {
  return cmd_as_ReportTerrainHeight();
}

struct CmdEnvelopeBuilder {
  typedef CmdEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_issued_by(::flatbuffers::Offset<::flatbuffers::String> issued_by) {
    fbb_.AddOffset(CmdEnvelope::VT_ISSUED_BY, issued_by);
  }
  void add_tick(int64_t tick) {
    fbb_.AddElement<int64_t>(CmdEnvelope::VT_TICK, tick, 0);
  }
  void add_cmd_type(acro::wire::Cmd cmd_type) {
    fbb_.AddElement<uint8_t>(CmdEnvelope::VT_CMD_TYPE, static_cast<uint8_t>(cmd_type), 0);
  }
  void add_cmd(::flatbuffers::Offset<void> cmd) {
    fbb_.AddOffset(CmdEnvelope::VT_CMD, cmd);
  }
  explicit CmdEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdEnvelope> CreateCmdEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> issued_by = 0,
    int64_t tick = 0,
    acro::wire::Cmd cmd_type = acro::wire::Cmd::NONE,
    ::flatbuffers::Offset<void> cmd = 0) {
  CmdEnvelopeBuilder builder_(_fbb);
  builder_.add_tick(tick);
  builder_.add_cmd(cmd);
  builder_.add_issued_by(issued_by);
  builder_.add_cmd_type(cmd_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CmdEnvelope> CreateCmdEnvelopeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *issued_by = nullptr,
    int64_t tick = 0,
    acro::wire::Cmd cmd_type = acro::wire::Cmd::NONE,
    ::flatbuffers::Offset<void> cmd = 0) {
  auto issued_by__ = issued_by ? _fbb.CreateString(issued_by) : 0;
  return acro::wire::CreateCmdEnvelope(
      _fbb,
      issued_by__,
      tick,
      cmd_type,
      cmd);
}

struct CommandFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AT = 4,
    VT_CMDS = 6
  };
  double at() const {
    return GetField<double>(VT_AT, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>> *cmds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>> *>(VT_CMDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_AT, 8) &&
           VerifyOffset(verifier, VT_CMDS) &&
           verifier.VerifyVector(cmds()) &&
           verifier.VerifyVectorOfTables(cmds()) &&
           verifier.EndTable();
  }
};

struct CommandFrameBuilder {
  typedef CommandFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_at(double at) {
    fbb_.AddElement<double>(CommandFrame::VT_AT, at, 0.0);
  }
  void add_cmds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>>> cmds) {
    fbb_.AddOffset(CommandFrame::VT_CMDS, cmds);
  }
  explicit CommandFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandFrame> CreateCommandFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double at = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>>> cmds = 0) {
  CommandFrameBuilder builder_(_fbb);
  builder_.add_at(at);
  builder_.add_cmds(cmds);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommandFrame> CreateCommandFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double at = 0.0,
    const std::vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>> *cmds = nullptr) {
  auto cmds__ = cmds ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::CmdEnvelope>>(*cmds) : 0;
  return acro::wire::CreateCommandFrame(
      _fbb,
      at,
      cmds__);
}

inline bool VerifyCmd(::flatbuffers::Verifier &verifier, const void *obj, Cmd type) {
  switch (type) {
    case Cmd::NONE: {
      return true;
    }
    case Cmd::SetThrottle: {
      auto ptr = reinterpret_cast<const acro::wire::SetThrottle *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::SeparateStage: {
      auto ptr = reinterpret_cast<const acro::wire::SeparateStage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::SetAttitude: {
      auto ptr = reinterpret_cast<const acro::wire::SetAttitude *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::PlaceBuilding: {
      auto ptr = reinterpret_cast<const acro::wire::PlaceBuilding *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::ReportTerrainHeight: {
      auto ptr = reinterpret_cast<const acro::wire::ReportTerrainHeight *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyCmdVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Cmd> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCmd(
        verifier,  values->Get(i), types->GetEnum<Cmd>(i))) {
      return false;
    }
  }
  return true;
}

inline const acro::wire::WorldFrame *GetWorldFrame(const void *buf) {
  return ::flatbuffers::GetRoot<acro::wire::WorldFrame>(buf);
}

inline const acro::wire::WorldFrame *GetSizePrefixedWorldFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<acro::wire::WorldFrame>(buf);
}

inline bool VerifyWorldFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<acro::wire::WorldFrame>(nullptr);
}

inline bool VerifySizePrefixedWorldFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<acro::wire::WorldFrame>(nullptr);
}

inline void FinishWorldFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<acro::wire::WorldFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWorldFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<acro::wire::WorldFrame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace wire
}  // namespace acro

#endif  // FLATBUFFERS_GENERATED_SIM_ACRO_WIRE_H_
