// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIM_ACRO_WIRE_H_
#define FLATBUFFERS_GENERATED_SIM_ACRO_WIRE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace acro {
namespace wire {

struct Vec3;

struct Quat;

struct PartFrame;
struct PartFrameBuilder;

struct VesselFrame;
struct VesselFrameBuilder;

struct BuildingFrame;
struct BuildingFrameBuilder;

struct BodyFrame;
struct BodyFrameBuilder;

struct WorldFrame;
struct WorldFrameBuilder;

struct SetThrottle;
struct SetThrottleBuilder;

struct SeparateStage;
struct SeparateStageBuilder;

struct SetAttitude;
struct SetAttitudeBuilder;

struct PlaceBuilding;
struct PlaceBuildingBuilder;

struct ReportTerrainHeight;
struct ReportTerrainHeightBuilder;

struct CmdEnvelope;
struct CmdEnvelopeBuilder;

struct CommandFrame;
struct CommandFrameBuilder;

enum class Cmd : uint8_t {
  NONE = 0,
  SetThrottle = 1,
  SeparateStage = 2,
  SetAttitude = 3,
  PlaceBuilding = 4,
  ReportTerrainHeight = 5,
  MIN = NONE,
  MAX = ReportTerrainHeight
};

inline const Cmd (&EnumValuesCmd())[6] {
  static const Cmd values[] = {
    Cmd::NONE,
    Cmd::SetThrottle,
    Cmd::SeparateStage,
    Cmd::SetAttitude,
    Cmd::PlaceBuilding,
    Cmd::ReportTerrainHeight
  };
  return values;
}

inline const char * const *EnumNamesCmd() {
  static const char * const names[7] = {
    "NONE",
    "SetThrottle",
    "SeparateStage",
    "SetAttitude",
    "PlaceBuilding",
    "ReportTerrainHeight",
    nullptr
  };
  return names;
}

inline const char *EnumNameCmd(Cmd e) {
  if (::flatbuffers::IsOutRange(e, Cmd::NONE, Cmd::ReportTerrainHeight)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCmd()[index];
}

template<typename T> struct CmdTraits {
  static const Cmd enum_value = Cmd::NONE;
};

template<> struct CmdTraits<acro::wire::SetThrottle> {
  static const Cmd enum_value = Cmd::SetThrottle;
};

template<> struct CmdTraits<acro::wire::SeparateStage> {
  static const Cmd enum_value = Cmd::SeparateStage;
};

template<> struct CmdTraits<acro::wire::SetAttitude> {
  static const Cmd enum_value = Cmd::SetAttitude;
};

template<> struct CmdTraits<acro::wire::PlaceBuilding> {
  static const Cmd enum_value = Cmd::PlaceBuilding;
};

template<> struct CmdTraits<acro::wire::ReportTerrainHeight> {
  static const Cmd enum_value = Cmd::ReportTerrainHeight;
};

bool VerifyCmd(::flatbuffers::Verifier &verifier, const void *obj, Cmd type);
bool VerifyCmdVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Cmd> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  double x_;
  double y_;
  double z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(double _x, double _y, double _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  double x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 24);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) Quat FLATBUFFERS_FINAL_CLASS {
 private:
  double w_;
  double x_;
  double y_;
  double z_;

 public:
  Quat()
      : w_(0),
        x_(0),
        y_(0),
        z_(0) {
  }
  Quat(double _w, double _x, double _y, double _z)
      : w_(::flatbuffers::EndianScalar(_w)),
        x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  double w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
  double x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  double y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  double z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Quat, 32);

struct PartFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_OFFSET = 8
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const acro::wire::Vec3 *offset() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_OFFSET);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_OFFSET, 8) &&
           verifier.EndTable();
  }
};

struct PartFrameBuilder {
  typedef PartFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(PartFrame::VT_ID, id);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(PartFrame::VT_TYPE, type);
  }
  void add_offset(const acro::wire::Vec3 *offset) {
    fbb_.AddStruct(PartFrame::VT_OFFSET, offset);
  }
  explicit PartFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PartFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PartFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PartFrame> CreatePartFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    const acro::wire::Vec3 *offset = nullptr) {
  PartFrameBuilder builder_(_fbb);
  builder_.add_offset(offset);
  builder_.add_type(type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PartFrame> CreatePartFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *type = nullptr,
    const acro::wire::Vec3 *offset = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  return acro::wire::CreatePartFrame(
      _fbb,
      id__,
      type__,
      offset);
}

struct VesselFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VesselFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_OWNER = 6,
    VT_BODY = 8,
    VT_POS = 10,
    VT_VEL = 12,
    VT_ATT = 14,
    VT_SPIN = 16,
    VT_THROTTLE = 18,
    VT_ON_RAILS = 20,
    VT_LANDED = 22,
    VT_PARTS = 24
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *owner() const {
    return GetPointer<const ::flatbuffers::String *>(VT_OWNER);
  }
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  const acro::wire::Vec3 *pos() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_POS);
  }
  const acro::wire::Vec3 *vel() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_VEL);
  }
  const acro::wire::Quat *att() const {
    return GetStruct<const acro::wire::Quat *>(VT_ATT);
  }
  const acro::wire::Vec3 *spin() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_SPIN);
  }
  double throttle() const {
    return GetField<double>(VT_THROTTLE, 0.0);
  }
  bool on_rails() const {
    return GetField<uint8_t>(VT_ON_RAILS, 0) != 0;
  }
  bool landed() const {
    return GetField<uint8_t>(VT_LANDED, 0) != 0;
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>> *parts() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>> *>(VT_PARTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_OWNER) &&
           verifier.VerifyString(owner()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_POS, 8) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_VEL, 8) &&
           VerifyField<acro::wire::Quat>(verifier, VT_ATT, 8) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_SPIN, 8) &&
           VerifyField<double>(verifier, VT_THROTTLE, 8) &&
           VerifyField<uint8_t>(verifier, VT_ON_RAILS, 1) &&
           VerifyField<uint8_t>(verifier, VT_LANDED, 1) &&
           VerifyOffset(verifier, VT_PARTS) &&
           verifier.VerifyVector(parts()) &&
           verifier.VerifyVectorOfTables(parts()) &&
           verifier.EndTable();
  }
};

struct VesselFrameBuilder {
  typedef VesselFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(VesselFrame::VT_ID, id);
  }
  void add_owner(::flatbuffers::Offset<::flatbuffers::String> owner) {
    fbb_.AddOffset(VesselFrame::VT_OWNER, owner);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(VesselFrame::VT_BODY, body);
  }
  void add_pos(const acro::wire::Vec3 *pos) {
    fbb_.AddStruct(VesselFrame::VT_POS, pos);
  }
  void add_vel(const acro::wire::Vec3 *vel) {
    fbb_.AddStruct(VesselFrame::VT_VEL, vel);
  }
  void add_att(const acro::wire::Quat *att) {
    fbb_.AddStruct(VesselFrame::VT_ATT, att);
  }
  void add_spin(const acro::wire::Vec3 *spin) {
    fbb_.AddStruct(VesselFrame::VT_SPIN, spin);
  }
  void add_throttle(double throttle) {
    fbb_.AddElement<double>(VesselFrame::VT_THROTTLE, throttle, 0.0);
  }
  void add_on_rails(bool on_rails) {
    fbb_.AddElement<uint8_t>(VesselFrame::VT_ON_RAILS, static_cast<uint8_t>(on_rails), 0);
  }
  void add_landed(bool landed) {
    fbb_.AddElement<uint8_t>(VesselFrame::VT_LANDED, static_cast<uint8_t>(landed), 0);
  }
  void add_parts(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>>> parts) {
    fbb_.AddOffset(VesselFrame::VT_PARTS, parts);
  }
  explicit VesselFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VesselFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VesselFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VesselFrame> CreateVesselFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> owner = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Vec3 *vel = nullptr,
    const acro::wire::Quat *att = nullptr,
    const acro::wire::Vec3 *spin = nullptr,
    double throttle = 0.0,
    bool on_rails = false,
    bool landed = false,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::PartFrame>>> parts = 0) {
  VesselFrameBuilder builder_(_fbb);
  builder_.add_throttle(throttle);
  builder_.add_parts(parts);
  builder_.add_spin(spin);
  builder_.add_att(att);
  builder_.add_vel(vel);
  builder_.add_pos(pos);
  builder_.add_body(body);
  builder_.add_owner(owner);
  builder_.add_id(id);
  builder_.add_landed(landed);
  builder_.add_on_rails(on_rails);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VesselFrame> CreateVesselFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *owner = nullptr,
    const char *body = nullptr,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Vec3 *vel = nullptr,
    const acro::wire::Quat *att = nullptr,
    const acro::wire::Vec3 *spin = nullptr,
    double throttle = 0.0,
    bool on_rails = false,
    bool landed = false,
    const std::vector<::flatbuffers::Offset<acro::wire::PartFrame>> *parts = nullptr) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto owner__ = owner ? _fbb.CreateString(owner) : 0;
  auto body__ = body ? _fbb.CreateString(body) : 0;
  auto parts__ = parts ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::PartFrame>>(*parts) : 0;
  return acro::wire::CreateVesselFrame(
      _fbb,
      id__,
      owner__,
      body__,
      pos,
      vel,
      att,
      spin,
      throttle,
      on_rails,
      landed,
      parts__);
}

struct BuildingFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BuildingFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_COLONY = 8,
    VT_BODY = 10,
    VT_POS = 12,
    VT_ORIENT = 14,
    VT_LAT = 16,
    VT_LON = 18
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const ::flatbuffers::String *type() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TYPE);
  }
  const ::flatbuffers::String *colony() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLONY);
  }
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  const acro::wire::Vec3 *pos() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_POS);
  }
  const acro::wire::Quat *orient() const {
    return GetStruct<const acro::wire::Quat *>(VT_ORIENT);
  }
  double lat() const {
    return GetField<double>(VT_LAT, 0.0);
  }
  double lon() const {
    return GetField<double>(VT_LON, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyString(type()) &&
           VerifyOffset(verifier, VT_COLONY) &&
           verifier.VerifyString(colony()) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_POS, 8) &&
           VerifyField<acro::wire::Quat>(verifier, VT_ORIENT, 8) &&
           VerifyField<double>(verifier, VT_LAT, 8) &&
           VerifyField<double>(verifier, VT_LON, 8) &&
           verifier.EndTable();
  }
};

struct BuildingFrameBuilder {
  typedef BuildingFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(BuildingFrame::VT_ID, id);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::String> type) {
    fbb_.AddOffset(BuildingFrame::VT_TYPE, type);
  }
  void add_colony(::flatbuffers::Offset<::flatbuffers::String> colony) {
    fbb_.AddOffset(BuildingFrame::VT_COLONY, colony);
  }
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(BuildingFrame::VT_BODY, body);
  }
  void add_pos(const acro::wire::Vec3 *pos) {
    fbb_.AddStruct(BuildingFrame::VT_POS, pos);
  }
  void add_orient(const acro::wire::Quat *orient) {
    fbb_.AddStruct(BuildingFrame::VT_ORIENT, orient);
  }
  void add_lat(double lat) {
    fbb_.AddElement<double>(BuildingFrame::VT_LAT, lat, 0.0);
  }
  void add_lon(double lon) {
    fbb_.AddElement<double>(BuildingFrame::VT_LON, lon, 0.0);
  }
  explicit BuildingFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BuildingFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BuildingFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BuildingFrame> CreateBuildingFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> colony = 0,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double lat = 0.0,
    double lon = 0.0) {
  BuildingFrameBuilder builder_(_fbb);
  builder_.add_lon(lon);
  builder_.add_lat(lat);
  builder_.add_orient(orient);
  builder_.add_pos(pos);
  builder_.add_body(body);
  builder_.add_colony(colony);
  builder_.add_type(type);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BuildingFrame> CreateBuildingFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const char *type = nullptr,
    const char *colony = nullptr,
    const char *body = nullptr,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double lat = 0.0,
    double lon = 0.0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  auto type__ = type ? _fbb.CreateString(type) : 0;
  auto colony__ = colony ? _fbb.CreateString(colony) : 0;
  auto body__ = body ? _fbb.CreateString(body) : 0;
  return acro::wire::CreateBuildingFrame(
      _fbb,
      id__,
      type__,
      colony__,
      body__,
      pos,
      orient,
      lat,
      lon);
}

struct BodyFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_POS = 6,
    VT_ORIENT = 8,
    VT_RADIUS = 10
  };
  const ::flatbuffers::String *id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ID);
  }
  const acro::wire::Vec3 *pos() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_POS);
  }
  const acro::wire::Quat *orient() const {
    return GetStruct<const acro::wire::Quat *>(VT_ORIENT);
  }
  double radius() const {
    return GetField<double>(VT_RADIUS, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ID) &&
           verifier.VerifyString(id()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_POS, 8) &&
           VerifyField<acro::wire::Quat>(verifier, VT_ORIENT, 8) &&
           VerifyField<double>(verifier, VT_RADIUS, 8) &&
           verifier.EndTable();
  }
};

struct BodyFrameBuilder {
  typedef BodyFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(::flatbuffers::Offset<::flatbuffers::String> id) {
    fbb_.AddOffset(BodyFrame::VT_ID, id);
  }
  void add_pos(const acro::wire::Vec3 *pos) {
    fbb_.AddStruct(BodyFrame::VT_POS, pos);
  }
  void add_orient(const acro::wire::Quat *orient) {
    fbb_.AddStruct(BodyFrame::VT_ORIENT, orient);
  }
  void add_radius(double radius) {
    fbb_.AddElement<double>(BodyFrame::VT_RADIUS, radius, 0.0);
  }
  explicit BodyFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BodyFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BodyFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BodyFrame> CreateBodyFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> id = 0,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double radius = 0.0) {
  BodyFrameBuilder builder_(_fbb);
  builder_.add_radius(radius);
  builder_.add_orient(orient);
  builder_.add_pos(pos);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BodyFrame> CreateBodyFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *id = nullptr,
    const acro::wire::Vec3 *pos = nullptr,
    const acro::wire::Quat *orient = nullptr,
    double radius = 0.0) {
  auto id__ = id ? _fbb.CreateString(id) : 0;
  return acro::wire::CreateBodyFrame(
      _fbb,
      id__,
      pos,
      orient,
      radius);
}

struct WorldFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef WorldFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TICK = 4,
    VT_EPOCH = 6,
    VT_FINGERPRINT = 8,
    VT_BODIES = 10,
    VT_VESSELS = 12,
    VT_BUILDINGS = 14
  };
  int64_t tick() const {
    return GetField<int64_t>(VT_TICK, 0);
  }
  double epoch() const {
    return GetField<double>(VT_EPOCH, 0.0);
  }
  const ::flatbuffers::String *fingerprint() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FINGERPRINT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>> *bodies() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>> *>(VT_BODIES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>> *vessels() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>> *>(VT_VESSELS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>> *buildings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>> *>(VT_BUILDINGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_TICK, 8) &&
           VerifyField<double>(verifier, VT_EPOCH, 8) &&
           VerifyOffset(verifier, VT_FINGERPRINT) &&
           verifier.VerifyString(fingerprint()) &&
           VerifyOffset(verifier, VT_BODIES) &&
           verifier.VerifyVector(bodies()) &&
           verifier.VerifyVectorOfTables(bodies()) &&
           VerifyOffset(verifier, VT_VESSELS) &&
           verifier.VerifyVector(vessels()) &&
           verifier.VerifyVectorOfTables(vessels()) &&
           VerifyOffset(verifier, VT_BUILDINGS) &&
           verifier.VerifyVector(buildings()) &&
           verifier.VerifyVectorOfTables(buildings()) &&
           verifier.EndTable();
  }
};

struct WorldFrameBuilder {
  typedef WorldFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_tick(int64_t tick) {
    fbb_.AddElement<int64_t>(WorldFrame::VT_TICK, tick, 0);
  }
  void add_epoch(double epoch) {
    fbb_.AddElement<double>(WorldFrame::VT_EPOCH, epoch, 0.0);
  }
  void add_fingerprint(::flatbuffers::Offset<::flatbuffers::String> fingerprint) {
    fbb_.AddOffset(WorldFrame::VT_FINGERPRINT, fingerprint);
  }
  void add_bodies(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>>> bodies) {
    fbb_.AddOffset(WorldFrame::VT_BODIES, bodies);
  }
  void add_vessels(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>>> vessels) {
    fbb_.AddOffset(WorldFrame::VT_VESSELS, vessels);
  }
  void add_buildings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>>> buildings) {
    fbb_.AddOffset(WorldFrame::VT_BUILDINGS, buildings);
  }
  explicit WorldFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<WorldFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<WorldFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<WorldFrame> CreateWorldFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t tick = 0,
    double epoch = 0.0,
    ::flatbuffers::Offset<::flatbuffers::String> fingerprint = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BodyFrame>>> bodies = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::VesselFrame>>> vessels = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::BuildingFrame>>> buildings = 0) {
  WorldFrameBuilder builder_(_fbb);
  builder_.add_epoch(epoch);
  builder_.add_tick(tick);
  builder_.add_buildings(buildings);
  builder_.add_vessels(vessels);
  builder_.add_bodies(bodies);
  builder_.add_fingerprint(fingerprint);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<WorldFrame> CreateWorldFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int64_t tick = 0,
    double epoch = 0.0,
    const char *fingerprint = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::BodyFrame>> *bodies = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::VesselFrame>> *vessels = nullptr,
    const std::vector<::flatbuffers::Offset<acro::wire::BuildingFrame>> *buildings = nullptr) {
  auto fingerprint__ = fingerprint ? _fbb.CreateString(fingerprint) : 0;
  auto bodies__ = bodies ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::BodyFrame>>(*bodies) : 0;
  auto vessels__ = vessels ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::VesselFrame>>(*vessels) : 0;
  auto buildings__ = buildings ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::BuildingFrame>>(*buildings) : 0;
  return acro::wire::CreateWorldFrame(
      _fbb,
      tick,
      epoch,
      fingerprint__,
      bodies__,
      vessels__,
      buildings__);
}

struct SetThrottle FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetThrottleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VESSEL = 4,
    VT_THROTTLE = 6
  };
  const ::flatbuffers::String *vessel() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VESSEL);
  }
  double throttle() const {
    return GetField<double>(VT_THROTTLE, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VESSEL) &&
           verifier.VerifyString(vessel()) &&
           VerifyField<double>(verifier, VT_THROTTLE, 8) &&
           verifier.EndTable();
  }
};

struct SetThrottleBuilder {
  typedef SetThrottle Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vessel(::flatbuffers::Offset<::flatbuffers::String> vessel) {
    fbb_.AddOffset(SetThrottle::VT_VESSEL, vessel);
  }
  void add_throttle(double throttle) {
    fbb_.AddElement<double>(SetThrottle::VT_THROTTLE, throttle, 0.0);
  }
  explicit SetThrottleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetThrottle> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetThrottle>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetThrottle> CreateSetThrottle(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> vessel = 0,
    double throttle = 0.0) {
  SetThrottleBuilder builder_(_fbb);
  builder_.add_throttle(throttle);
  builder_.add_vessel(vessel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetThrottle> CreateSetThrottleDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *vessel = nullptr,
    double throttle = 0.0) {
  auto vessel__ = vessel ? _fbb.CreateString(vessel) : 0;
  return acro::wire::CreateSetThrottle(
      _fbb,
      vessel__,
      throttle);
}

struct SeparateStage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SeparateStageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VESSEL = 4
  };
  const ::flatbuffers::String *vessel() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VESSEL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VESSEL) &&
           verifier.VerifyString(vessel()) &&
           verifier.EndTable();
  }
};

struct SeparateStageBuilder {
  typedef SeparateStage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vessel(::flatbuffers::Offset<::flatbuffers::String> vessel) {
    fbb_.AddOffset(SeparateStage::VT_VESSEL, vessel);
  }
  explicit SeparateStageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SeparateStage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SeparateStage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SeparateStage> CreateSeparateStage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> vessel = 0) {
  SeparateStageBuilder builder_(_fbb);
  builder_.add_vessel(vessel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SeparateStage> CreateSeparateStageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *vessel = nullptr) {
  auto vessel__ = vessel ? _fbb.CreateString(vessel) : 0;
  return acro::wire::CreateSeparateStage(
      _fbb,
      vessel__);
}

struct SetAttitude FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SetAttitudeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VESSEL = 4,
    VT_HEADING = 6
  };
  const ::flatbuffers::String *vessel() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VESSEL);
  }
  const acro::wire::Vec3 *heading() const {
    return GetStruct<const acro::wire::Vec3 *>(VT_HEADING);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VESSEL) &&
           verifier.VerifyString(vessel()) &&
           VerifyField<acro::wire::Vec3>(verifier, VT_HEADING, 8) &&
           verifier.EndTable();
  }
};

struct SetAttitudeBuilder {
  typedef SetAttitude Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vessel(::flatbuffers::Offset<::flatbuffers::String> vessel) {
    fbb_.AddOffset(SetAttitude::VT_VESSEL, vessel);
  }
  void add_heading(const acro::wire::Vec3 *heading) {
    fbb_.AddStruct(SetAttitude::VT_HEADING, heading);
  }
  explicit SetAttitudeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SetAttitude> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SetAttitude>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SetAttitude> CreateSetAttitude(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> vessel = 0,
    const acro::wire::Vec3 *heading = nullptr) {
  SetAttitudeBuilder builder_(_fbb);
  builder_.add_heading(heading);
  builder_.add_vessel(vessel);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SetAttitude> CreateSetAttitudeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *vessel = nullptr,
    const acro::wire::Vec3 *heading = nullptr) {
  auto vessel__ = vessel ? _fbb.CreateString(vessel) : 0;
  return acro::wire::CreateSetAttitude(
      _fbb,
      vessel__,
      heading);
}

struct PlaceBuilding FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlaceBuildingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLONY = 4,
    VT_KIND = 6,
    VT_GX = 8,
    VT_GY = 10
  };
  const ::flatbuffers::String *colony() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COLONY);
  }
  const ::flatbuffers::String *kind() const {
    return GetPointer<const ::flatbuffers::String *>(VT_KIND);
  }
  int32_t gx() const {
    return GetField<int32_t>(VT_GX, 0);
  }
  int32_t gy() const {
    return GetField<int32_t>(VT_GY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_COLONY) &&
           verifier.VerifyString(colony()) &&
           VerifyOffset(verifier, VT_KIND) &&
           verifier.VerifyString(kind()) &&
           VerifyField<int32_t>(verifier, VT_GX, 4) &&
           VerifyField<int32_t>(verifier, VT_GY, 4) &&
           verifier.EndTable();
  }
};

struct PlaceBuildingBuilder {
  typedef PlaceBuilding Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_colony(::flatbuffers::Offset<::flatbuffers::String> colony) {
    fbb_.AddOffset(PlaceBuilding::VT_COLONY, colony);
  }
  void add_kind(::flatbuffers::Offset<::flatbuffers::String> kind) {
    fbb_.AddOffset(PlaceBuilding::VT_KIND, kind);
  }
  void add_gx(int32_t gx) {
    fbb_.AddElement<int32_t>(PlaceBuilding::VT_GX, gx, 0);
  }
  void add_gy(int32_t gy) {
    fbb_.AddElement<int32_t>(PlaceBuilding::VT_GY, gy, 0);
  }
  explicit PlaceBuildingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlaceBuilding> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlaceBuilding>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlaceBuilding> CreatePlaceBuilding(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> colony = 0,
    ::flatbuffers::Offset<::flatbuffers::String> kind = 0,
    int32_t gx = 0,
    int32_t gy = 0) {
  PlaceBuildingBuilder builder_(_fbb);
  builder_.add_gy(gy);
  builder_.add_gx(gx);
  builder_.add_kind(kind);
  builder_.add_colony(colony);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<PlaceBuilding> CreatePlaceBuildingDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *colony = nullptr,
    const char *kind = nullptr,
    int32_t gx = 0,
    int32_t gy = 0) {
  auto colony__ = colony ? _fbb.CreateString(colony) : 0;
  auto kind__ = kind ? _fbb.CreateString(kind) : 0;
  return acro::wire::CreatePlaceBuilding(
      _fbb,
      colony__,
      kind__,
      gx,
      gy);
}

struct ReportTerrainHeight FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ReportTerrainHeightBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BODY = 4,
    VT_LAT = 6,
    VT_LON = 8,
    VT_HEIGHT = 10
  };
  const ::flatbuffers::String *body() const {
    return GetPointer<const ::flatbuffers::String *>(VT_BODY);
  }
  double lat() const {
    return GetField<double>(VT_LAT, 0.0);
  }
  double lon() const {
    return GetField<double>(VT_LON, 0.0);
  }
  double height() const {
    return GetField<double>(VT_HEIGHT, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyString(body()) &&
           VerifyField<double>(verifier, VT_LAT, 8) &&
           VerifyField<double>(verifier, VT_LON, 8) &&
           VerifyField<double>(verifier, VT_HEIGHT, 8) &&
           verifier.EndTable();
  }
};

struct ReportTerrainHeightBuilder {
  typedef ReportTerrainHeight Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_body(::flatbuffers::Offset<::flatbuffers::String> body) {
    fbb_.AddOffset(ReportTerrainHeight::VT_BODY, body);
  }
  void add_lat(double lat) {
    fbb_.AddElement<double>(ReportTerrainHeight::VT_LAT, lat, 0.0);
  }
  void add_lon(double lon) {
    fbb_.AddElement<double>(ReportTerrainHeight::VT_LON, lon, 0.0);
  }
  void add_height(double height) {
    fbb_.AddElement<double>(ReportTerrainHeight::VT_HEIGHT, height, 0.0);
  }
  explicit ReportTerrainHeightBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ReportTerrainHeight> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ReportTerrainHeight>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ReportTerrainHeight> CreateReportTerrainHeight(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> body = 0,
    double lat = 0.0,
    double lon = 0.0,
    double height = 0.0) {
  ReportTerrainHeightBuilder builder_(_fbb);
  builder_.add_height(height);
  builder_.add_lon(lon);
  builder_.add_lat(lat);
  builder_.add_body(body);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ReportTerrainHeight> CreateReportTerrainHeightDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *body = nullptr,
    double lat = 0.0,
    double lon = 0.0,
    double height = 0.0) {
  auto body__ = body ? _fbb.CreateString(body) : 0;
  return acro::wire::CreateReportTerrainHeight(
      _fbb,
      body__,
      lat,
      lon,
      height);
}

struct CmdEnvelope FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CmdEnvelopeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ISSUED_BY = 4,
    VT_TICK = 6,
    VT_CMD_TYPE = 8,
    VT_CMD = 10
  };
  const ::flatbuffers::String *issued_by() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ISSUED_BY);
  }
  int64_t tick() const {
    return GetField<int64_t>(VT_TICK, 0);
  }
  acro::wire::Cmd cmd_type() const {
    return static_cast<acro::wire::Cmd>(GetField<uint8_t>(VT_CMD_TYPE, 0));
  }
  const void *cmd() const {
    return GetPointer<const void *>(VT_CMD);
  }
  template<typename T> const T *cmd_as() const;
  const acro::wire::SetThrottle *cmd_as_SetThrottle() const {
    return cmd_type() == acro::wire::Cmd::SetThrottle ? static_cast<const acro::wire::SetThrottle *>(cmd()) : nullptr;
  }
  const acro::wire::SeparateStage *cmd_as_SeparateStage() const {
    return cmd_type() == acro::wire::Cmd::SeparateStage ? static_cast<const acro::wire::SeparateStage *>(cmd()) : nullptr;
  }
  const acro::wire::SetAttitude *cmd_as_SetAttitude() const {
    return cmd_type() == acro::wire::Cmd::SetAttitude ? static_cast<const acro::wire::SetAttitude *>(cmd()) : nullptr;
  }
  const acro::wire::PlaceBuilding *cmd_as_PlaceBuilding() const {
    return cmd_type() == acro::wire::Cmd::PlaceBuilding ? static_cast<const acro::wire::PlaceBuilding *>(cmd()) : nullptr;
  }
  const acro::wire::ReportTerrainHeight *cmd_as_ReportTerrainHeight() const {
    return cmd_type() == acro::wire::Cmd::ReportTerrainHeight ? static_cast<const acro::wire::ReportTerrainHeight *>(cmd()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ISSUED_BY) &&
           verifier.VerifyString(issued_by()) &&
           VerifyField<int64_t>(verifier, VT_TICK, 8) &&
           VerifyField<uint8_t>(verifier, VT_CMD_TYPE, 1) &&
           VerifyOffset(verifier, VT_CMD) &&
           VerifyCmd(verifier, cmd(), cmd_type()) &&
           verifier.EndTable();
  }
};

template<> inline const acro::wire::SetThrottle *CmdEnvelope::cmd_as<acro::wire::SetThrottle>() const {
  return cmd_as_SetThrottle();
}

template<> inline const acro::wire::SeparateStage *CmdEnvelope::cmd_as<acro::wire::SeparateStage>() const {
  return cmd_as_SeparateStage();
}

template<> inline const acro::wire::SetAttitude *CmdEnvelope::cmd_as<acro::wire::SetAttitude>() const {
  return cmd_as_SetAttitude();
}

template<> inline const acro::wire::PlaceBuilding *CmdEnvelope::cmd_as<acro::wire::PlaceBuilding>() const {
  return cmd_as_PlaceBuilding();
}

template<> inline const acro::wire::ReportTerrainHeight *CmdEnvelope::cmd_as<acro::wire::ReportTerrainHeight>() const {
  return cmd_as_ReportTerrainHeight();
}

struct CmdEnvelopeBuilder {
  typedef CmdEnvelope Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_issued_by(::flatbuffers::Offset<::flatbuffers::String> issued_by) {
    fbb_.AddOffset(CmdEnvelope::VT_ISSUED_BY, issued_by);
  }
  void add_tick(int64_t tick) {
    fbb_.AddElement<int64_t>(CmdEnvelope::VT_TICK, tick, 0);
  }
  void add_cmd_type(acro::wire::Cmd cmd_type) {
    fbb_.AddElement<uint8_t>(CmdEnvelope::VT_CMD_TYPE, static_cast<uint8_t>(cmd_type), 0);
  }
  void add_cmd(::flatbuffers::Offset<void> cmd) {
    fbb_.AddOffset(CmdEnvelope::VT_CMD, cmd);
  }
  explicit CmdEnvelopeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CmdEnvelope> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CmdEnvelope>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CmdEnvelope> CreateCmdEnvelope(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> issued_by = 0,
    int64_t tick = 0,
    acro::wire::Cmd cmd_type = acro::wire::Cmd::NONE,
    ::flatbuffers::Offset<void> cmd = 0) {
  CmdEnvelopeBuilder builder_(_fbb);
  builder_.add_tick(tick);
  builder_.add_cmd(cmd);
  builder_.add_issued_by(issued_by);
  builder_.add_cmd_type(cmd_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CmdEnvelope> CreateCmdEnvelopeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *issued_by = nullptr,
    int64_t tick = 0,
    acro::wire::Cmd cmd_type = acro::wire::Cmd::NONE,
    ::flatbuffers::Offset<void> cmd = 0) {
  auto issued_by__ = issued_by ? _fbb.CreateString(issued_by) : 0;
  return acro::wire::CreateCmdEnvelope(
      _fbb,
      issued_by__,
      tick,
      cmd_type,
      cmd);
}

struct CommandFrame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CommandFrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AT = 4,
    VT_CMDS = 6
  };
  double at() const {
    return GetField<double>(VT_AT, 0.0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>> *cmds() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>> *>(VT_CMDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_AT, 8) &&
           VerifyOffset(verifier, VT_CMDS) &&
           verifier.VerifyVector(cmds()) &&
           verifier.VerifyVectorOfTables(cmds()) &&
           verifier.EndTable();
  }
};

struct CommandFrameBuilder {
  typedef CommandFrame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_at(double at) {
    fbb_.AddElement<double>(CommandFrame::VT_AT, at, 0.0);
  }
  void add_cmds(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>>> cmds) {
    fbb_.AddOffset(CommandFrame::VT_CMDS, cmds);
  }
  explicit CommandFrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CommandFrame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CommandFrame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CommandFrame> CreateCommandFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double at = 0.0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>>> cmds = 0) {
  CommandFrameBuilder builder_(_fbb);
  builder_.add_at(at);
  builder_.add_cmds(cmds);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CommandFrame> CreateCommandFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double at = 0.0,
    const std::vector<::flatbuffers::Offset<acro::wire::CmdEnvelope>> *cmds = nullptr) {
  auto cmds__ = cmds ? _fbb.CreateVector<::flatbuffers::Offset<acro::wire::CmdEnvelope>>(*cmds) : 0;
  return acro::wire::CreateCommandFrame(
      _fbb,
      at,
      cmds__);
}

inline bool VerifyCmd(::flatbuffers::Verifier &verifier, const void *obj, Cmd type) {
  switch (type) {
    case Cmd::NONE: {
      return true;
    }
    case Cmd::SetThrottle: {
      auto ptr = reinterpret_cast<const acro::wire::SetThrottle *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::SeparateStage: {
      auto ptr = reinterpret_cast<const acro::wire::SeparateStage *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::SetAttitude: {
      auto ptr = reinterpret_cast<const acro::wire::SetAttitude *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::PlaceBuilding: {
      auto ptr = reinterpret_cast<const acro::wire::PlaceBuilding *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Cmd::ReportTerrainHeight: {
      auto ptr = reinterpret_cast<const acro::wire::ReportTerrainHeight *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyCmdVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Cmd> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyCmd(
        verifier,  values->Get(i), types->GetEnum<Cmd>(i))) {
      return false;
    }
  }
  return true;
}

inline const acro::wire::WorldFrame *GetWorldFrame(const void *buf) {
  return ::flatbuffers::GetRoot<acro::wire::WorldFrame>(buf);
}

inline const acro::wire::WorldFrame *GetSizePrefixedWorldFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<acro::wire::WorldFrame>(buf);
}

inline bool VerifyWorldFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<acro::wire::WorldFrame>(nullptr);
}

inline bool VerifySizePrefixedWorldFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<acro::wire::WorldFrame>(nullptr);
}

inline void FinishWorldFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<acro::wire::WorldFrame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedWorldFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<acro::wire::WorldFrame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace wire
}  // namespace acro

#endif  // FLATBUFFERS_GENERATED_SIM_ACRO_WIRE_H_
