/// Residential / Commercial / Industrial demand for a city, each 0..1. The
/// Cities-Skylines "RCI" gauge: high demand pulls new buildings into matching
/// zones. Demand is generated by population pressure, jobs, trade, and (in this
/// sim) by arriving flights creating commerce/relaxation/industry needs.
class CityDemand {
  final double residential;
  final double commercial;
  final double industrial;

  const CityDemand({
    this.residential = 0,
    this.commercial = 0,
    this.industrial = 0,
  });

  static const CityDemand none = CityDemand();

  CityDemand copyWith({double? residential, double? commercial, double? industrial}) =>
      CityDemand(
        residential: (residential ?? this.residential).clamp(0.0, 1.0),
        commercial: (commercial ?? this.commercial).clamp(0.0, 1.0),
        industrial: (industrial ?? this.industrial).clamp(0.0, 1.0),
      );

  /// Add demand (clamped to [0,1]). Used by flight arrivals + population pressure.
  CityDemand add({double residential = 0, double commercial = 0, double industrial = 0}) =>
      CityDemand(
        residential: (this.residential + residential).clamp(0.0, 1.0),
        commercial: (this.commercial + commercial).clamp(0.0, 1.0),
        industrial: (this.industrial + industrial).clamp(0.0, 1.0),
      );
}
