// Generates the Unreal FSim* USTRUCT mirror of the render-frame tables in
// wire/sim.fbs, so the engine-facing structs stay in sync with the wire schema.
//
//   dart run tool/gen_ue_bindings.dart
//
// Types come from the schema; field NAMES come from the [structs] config below
// (the wire names are terse and the UE/BP names are nicer, and a few carry
// table-specific semantics — Building.pos is body-LOCAL, Vessel.pos is
// world-rebased — that the schema can't express). The generator VALIDATES drift:
// if a render table gains a field with no mapping here (or a mapping points at a
// field the schema doesn't have), it fails loudly — so you can't widen the wire
// and forget the UE side. The ingest/rebasing logic stays hand-written in
// SpaceSimSubsystem.cpp; only the data structs are generated.
import 'dart:io';

/// UE struct <- wire table, with the wire-field -> UE-field-name mapping.
const structs = <_Struct>[
  _Struct('FSimPart', 'PartFrame', 'One part of a craft (asset key + craft-local offset).', {
    'id': 'Id',
    'type': 'Type',
    'offset': 'LocalOffset',
  }),
  _Struct('FSimResource', 'ResourceFrame', 'Aggregated resource gauge (summed across parts by type).', {
    'type': 'Type',
    'amount': 'Amount',
    'capacity': 'Capacity',
  }),
  _Struct('FSimBody', 'BodyFrame', 'A celestial body, world-space + rebased onto the focus body.', {
    'id': 'Id',
    'pos': 'Position',
    'orient': 'Orientation',
    'radius': 'RadiusCm',
  }),
  _Struct('FSimVessel', 'VesselFrame', 'A vessel, world-space + rebased; Parts compose the craft.', {
    'id': 'Id',
    'owner': 'Owner',
    'body': 'Body',
    'pos': 'Position',
    'vel': 'Velocity',
    'att': 'Attitude',
    'spin': 'AngularVelocity',
    'throttle': 'Throttle',
    'on_rails': 'bOnRails',
    'landed': 'bLanded',
    'parts': 'Parts',
    'mass': 'MassKg',
    'crew': 'Crew',
    'resources': 'Resources',
    'max_temp': 'MaxTempK',
    'temp_limit': 'TempLimitK',
  }),
  _Struct('FSimBuilding', 'BuildingFrame', 'A colony building, body-LOCAL (parent under the body actor).', {
    'id': 'Id',
    'type': 'Type',
    'colony': 'Colony',
    'body': 'Body',
    'pos': 'LocalPosition',
    'orient': 'LocalOrientation',
    'lat': 'Lat',
    'lon': 'Lon',
  }),
  _Struct('FSimEvent', 'EventFrame', 'A discrete sim event that fired this tick (switch on Kind).', {
    'kind': 'Kind',
    'subject': 'Subject',
    'target': 'Target',
    'magnitude': 'Magnitude',
    'info': 'Info',
  }),
];

class _Struct {
  final String name;
  final String table;
  final String doc;
  final Map<String, String> fields; // wireName -> ueName (ordered)
  const _Struct(this.name, this.table, this.doc, this.fields);
}

class _Field {
  final String name;
  final String type;
  const _Field(this.name, this.type);
}

Never fail(String msg) {
  stderr.writeln('gen_ue_bindings: $msg');
  exit(1);
}

void main() {
  final fbs = File('wire/sim.fbs');
  if (!fbs.existsSync()) fail('run from the repo root (wire/sim.fbs not found)');
  final tables = _parseTables(fbs.readAsStringSync());

  // Map a wire table name to the generating UE struct, for [X] field nesting.
  final tableToStruct = {for (final s in structs) s.table: s.name};

  final buf = StringBuffer()
    ..writeln('// GENERATED by tool/gen_ue_bindings.dart from wire/sim.fbs — DO NOT EDIT.')
    ..writeln('// Regenerate: dart run tool/gen_ue_bindings.dart')
    ..writeln('#pragma once')
    ..writeln()
    ..writeln('#include "CoreMinimal.h"')
    ..writeln('#include "AcroSimTypes.generated.h"')
    ..writeln();

  final emitted = <String>{};
  for (final s in structs) {
    final schema = tables[s.table];
    if (schema == null) fail('schema has no table "${s.table}" for ${s.name}');
    final schemaNames = {for (final f in schema) f.name};

    // Drift checks, both directions.
    for (final w in s.fields.keys) {
      if (!schemaNames.contains(w)) {
        fail('${s.name}: mapped field "$w" is not in table ${s.table}');
      }
    }
    for (final f in schema) {
      if (!s.fields.containsKey(f.name)) {
        fail('${s.table}.${f.name} has no UE mapping in ${s.name} — '
            'add it to tool/gen_ue_bindings.dart (you widened the wire; finish the UE side).');
      }
    }

    buf.writeln('/// ${s.doc}');
    buf.writeln('USTRUCT(BlueprintType)');
    buf.writeln('struct ${s.name}');
    buf.writeln('{');
    buf.writeln('\tGENERATED_BODY()');
    for (final f in schema) {
      final ue = s.fields[f.name]!;
      final (cppType, def) = _ueType(f.type, tableToStruct);
      // A nested struct must be emitted before the struct that holds it.
      if (cppType.startsWith('TArray<') &&
          !emitted.contains(cppType.substring(7, cppType.length - 1))) {
        fail('${s.name}.$ue uses $cppType before it is defined — '
            'reorder `structs` in tool/gen_ue_bindings.dart so nested types come first.');
      }
      final defClause = def == null ? '' : ' = $def';
      buf.writeln('\tUPROPERTY(BlueprintReadOnly) $cppType $ue$defClause;');
    }
    buf.writeln('};');
    buf.writeln();
    emitted.add(s.name);
  }

  final dest = File('ue/AcroSimBridge/Source/AcroSimBridge/Public/AcroSimTypes.h');
  dest.writeAsStringSync(buf.toString());
  stdout.writeln('wrote ${dest.path} (${structs.length} structs)');
}

/// (cppType, defaultExpr?) for a wire field type.
(String, String?) _ueType(String t, Map<String, String> tableToStruct) {
  if (t.startsWith('[') && t.endsWith(']')) {
    final inner = t.substring(1, t.length - 1);
    final st = tableToStruct[inner];
    if (st == null) throw StateError('list of unmapped table "$inner"');
    return ('TArray<$st>', null);
  }
  switch (t) {
    case 'double':
    case 'float':
      return ('float', '0.f');
    case 'int':
    case 'int32':
      return ('int32', '0');
    case 'long':
    case 'int64':
      return ('int64', '0');
    case 'bool':
      return ('bool', 'false');
    case 'string':
      return ('FString', null);
    case 'Vec3':
      return ('FVector', 'FVector::ZeroVector');
    case 'Quat':
      return ('FQuat', 'FQuat::Identity');
    default:
      throw StateError('unhandled wire type "$t"');
  }
}

/// Minimal sim.fbs table parser: { tableName: [(field, type)] }.
Map<String, List<_Field>> _parseTables(String src) {
  // Strip // line comments.
  final clean = src.replaceAll(RegExp(r'//[^\n]*'), '');
  final out = <String, List<_Field>>{};
  final re = RegExp(r'table\s+(\w+)\s*\{([^}]*)\}', multiLine: true);
  for (final m in re.allMatches(clean)) {
    final name = m.group(1)!;
    final body = m.group(2)!;
    final fields = <_Field>[];
    for (final raw in body.split(';')) {
      final line = raw.trim();
      if (line.isEmpty || !line.contains(':')) continue;
      final i = line.indexOf(':');
      final fname = line.substring(0, i).trim();
      // type is up to a '(' attribute or '= default' suffix.
      var type = line.substring(i + 1).trim();
      for (final sep in const ['(', '=']) {
        final k = type.indexOf(sep);
        if (k >= 0) type = type.substring(0, k).trim();
      }
      fields.add(_Field(fname, type));
    }
    out[name] = fields;
  }
  return out;
}
